/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization;

import com.auth0.client.myorganization.core.ClientOptions;
import com.auth0.client.myorganization.core.Suppliers;
import com.auth0.client.myorganization.organization.AsyncOrganizationClient;
import java.util.function.Supplier;

public class AsyncMyOrganizationApi {
    protected final ClientOptions clientOptions;

    protected final Supplier<AsyncOrganizationDetailsClient> organizationDetailsClient;

    protected final Supplier<AsyncOrganizationClient> organizationClient;

    public AsyncMyOrganizationApi(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.organizationDetailsClient = Suppliers.memoize(() -> new AsyncOrganizationDetailsClient(clientOptions));
        this.organizationClient = Suppliers.memoize(() -> new AsyncOrganizationClient(clientOptions));
    }

    public AsyncOrganizationDetailsClient organizationDetails() {
        return this.organizationDetailsClient.get();
    }

    public AsyncOrganizationClient organization() {
        return this.organizationClient.get();
    }

    public static AsyncMyOrganizationApiBuilder builder() {
        return new AsyncMyOrganizationApiBuilder();
    }
}
