/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization;

import com.auth0.client.myorganization.core.ClientOptions;
import com.auth0.client.myorganization.core.Suppliers;
import com.auth0.client.myorganization.organization.OrganizationClient;
import java.util.function.Supplier;

public class MyOrganizationApi {
    protected final ClientOptions clientOptions;

    protected final Supplier<OrganizationDetailsClient> organizationDetailsClient;

    protected final Supplier<OrganizationClient> organizationClient;

    public MyOrganizationApi(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.organizationDetailsClient = Suppliers.memoize(() -> new OrganizationDetailsClient(clientOptions));
        this.organizationClient = Suppliers.memoize(() -> new OrganizationClient(clientOptions));
    }

    public OrganizationDetailsClient organizationDetails() {
        return this.organizationDetailsClient.get();
    }

    public OrganizationClient organization() {
        return this.organizationClient.get();
    }

    public static MyOrganizationApiBuilder builder() {
        return new MyOrganizationApiBuilder();
    }
}
