/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization;

import com.auth0.client.myorganization.core.ClientOptions;
import com.auth0.client.myorganization.core.RequestOptions;
import com.auth0.client.myorganization.types.OrgDetails;
import com.auth0.client.myorganization.types.OrgDetailsRead;

public class OrganizationDetailsClient {
    protected final ClientOptions clientOptions;

    private final RawOrganizationDetailsClient rawClient;

    public OrganizationDetailsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawOrganizationDetailsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawOrganizationDetailsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieve details for this Organization, including display name and branding options. To learn more about Auth0 Organizations, read <a href="https://auth0.com/docs/manage-users/organizations">Organizations</a>.
     */
    public OrgDetailsRead get() {
        return this.rawClient.get().body();
    }

    /**
     * Retrieve details for this Organization, including display name and branding options. To learn more about Auth0 Organizations, read <a href="https://auth0.com/docs/manage-users/organizations">Organizations</a>.
     */
    public OrgDetailsRead get(RequestOptions requestOptions) {
        return this.rawClient.get(requestOptions).body();
    }

    /**
     * Update details for this Organization, such as display name and branding options. To learn more about Auth0 Organizations, read <a href="https://auth0.com/docs/manage-users/organizations">Organizations</a>.
     */
    public OrgDetailsRead update() {
        return this.rawClient.update().body();
    }

    /**
     * Update details for this Organization, such as display name and branding options. To learn more about Auth0 Organizations, read <a href="https://auth0.com/docs/manage-users/organizations">Organizations</a>.
     */
    public OrgDetailsRead update(RequestOptions requestOptions) {
        return this.rawClient.update(requestOptions).body();
    }

    /**
     * Update details for this Organization, such as display name and branding options. To learn more about Auth0 Organizations, read <a href="https://auth0.com/docs/manage-users/organizations">Organizations</a>.
     */
    public OrgDetailsRead update(OrgDetails request) {
        return this.rawClient.update(request).body();
    }

    /**
     * Update details for this Organization, such as display name and branding options. To learn more about Auth0 Organizations, read <a href="https://auth0.com/docs/manage-users/organizations">Organizations</a>.
     */
    public OrgDetailsRead update(OrgDetails request, RequestOptions requestOptions) {
        return this.rawClient.update(request, requestOptions).body();
    }
}
