/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.organization.identityproviders.types;

import com.auth0.client.myorganization.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateIdpDomainRequestContent.Builder.class)
public final class CreateIdpDomainRequestContent {
    private final String domain;

    private final Map<String, Object> additionalProperties;

    private CreateIdpDomainRequestContent(String domain, Map<String, Object> additionalProperties) {
        this.domain = domain;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("domain")
    public String getDomain() {
        return domain;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateIdpDomainRequestContent && equalTo((CreateIdpDomainRequestContent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateIdpDomainRequestContent other) {
        return domain.equals(other.domain);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.domain);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static DomainStage builder() {
        return new Builder();
    }

    public interface DomainStage {
        _FinalStage domain(@NotNull String domain);

        Builder from(CreateIdpDomainRequestContent other);
    }

    public interface _FinalStage {
        CreateIdpDomainRequestContent build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements DomainStage, _FinalStage {
        private String domain;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @Override
        public Builder from(CreateIdpDomainRequestContent other) {
            domain(other.getDomain());
            return this;
        }

        @Override
        @JsonSetter("domain")
        public _FinalStage domain(@NotNull String domain) {
            this.domain = Objects.requireNonNull(domain, "domain must not be null");
            return this;
        }

        @Override
        public CreateIdpDomainRequestContent build() {
            return new CreateIdpDomainRequestContent(domain, additionalProperties);
        }

        @Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
