/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.organization.identityproviders.provisioning;

import com.auth0.client.myorganization.core.ClientOptions;
import com.auth0.client.myorganization.core.MediaTypes;
import com.auth0.client.myorganization.core.MyOrganizationApiException;
import com.auth0.client.myorganization.core.MyOrganizationApiHttpResponse;
import com.auth0.client.myorganization.core.MyOrganizationException;
import com.auth0.client.myorganization.core.ObjectMappers;
import com.auth0.client.myorganization.core.RequestOptions;
import com.auth0.client.myorganization.errors.BadRequestError;
import com.auth0.client.myorganization.errors.ForbiddenError;
import com.auth0.client.myorganization.errors.NotFoundError;
import com.auth0.client.myorganization.errors.TooManyRequestsError;
import com.auth0.client.myorganization.errors.UnauthorizedError;
import com.auth0.client.myorganization.organization.identityproviders.provisioning.types.CreateIdpProvisioningScimTokenRequestContent;
import com.auth0.client.myorganization.types.ErrorResponseContent;
import com.auth0.client.myorganization.types.IdpScimTokenCreate;
import com.auth0.client.myorganization.types.ListIdpProvisioningScimTokensResponseContent;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawScimTokensClient {
    protected final ClientOptions clientOptions;

    public RawScimTokensClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Retrieve a list of <a href="https://auth0.com/docs/authenticate/protocols/scim/configure-inbound-scim#scim-endpoints-and-tokens">SCIM tokens</a> for the Provisioning Configuration of an Identity Provider specified by ID for this Organization.
     */
    public MyOrganizationApiHttpResponse<ListIdpProvisioningScimTokensResponseContent> list(String idpId) {
        return list(idpId, null);
    }

    /**
     * Retrieve a list of <a href="https://auth0.com/docs/authenticate/protocols/scim/configure-inbound-scim#scim-endpoints-and-tokens">SCIM tokens</a> for the Provisioning Configuration of an Identity Provider specified by ID for this Organization.
     */
    public MyOrganizationApiHttpResponse<ListIdpProvisioningScimTokensResponseContent> list(
            String idpId, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("identity-providers")
                .addPathSegment(idpId)
                .addPathSegments("provisioning")
                .addPathSegments("scim-tokens");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MyOrganizationApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(
                                responseBodyString, ListIdpProvisioningScimTokensResponseContent.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponseContent.class),
                                response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponseContent.class),
                                response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponseContent.class),
                                response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponseContent.class),
                                response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MyOrganizationApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new MyOrganizationException("Network error executing HTTP request", e);
        }
    }

    /**
     * Create a new SCIM token for the Provisioning Configuration of an Identity Provider specified by ID for this Organization.
     */
    public MyOrganizationApiHttpResponse<IdpScimTokenCreate> create(String idpId) {
        return create(
                idpId, CreateIdpProvisioningScimTokenRequestContent.builder().build());
    }

    /**
     * Create a new SCIM token for the Provisioning Configuration of an Identity Provider specified by ID for this Organization.
     */
    public MyOrganizationApiHttpResponse<IdpScimTokenCreate> create(String idpId, RequestOptions requestOptions) {
        return create(
                idpId, CreateIdpProvisioningScimTokenRequestContent.builder().build(), requestOptions);
    }

    /**
     * Create a new SCIM token for the Provisioning Configuration of an Identity Provider specified by ID for this Organization.
     */
    public MyOrganizationApiHttpResponse<IdpScimTokenCreate> create(
            String idpId, CreateIdpProvisioningScimTokenRequestContent request) {
        return create(idpId, request, null);
    }

    /**
     * Create a new SCIM token for the Provisioning Configuration of an Identity Provider specified by ID for this Organization.
     */
    public MyOrganizationApiHttpResponse<IdpScimTokenCreate> create(
            String idpId, CreateIdpProvisioningScimTokenRequestContent request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("identity-providers")
                .addPathSegment(idpId)
                .addPathSegments("provisioning")
                .addPathSegments("scim-tokens");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new MyOrganizationException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MyOrganizationApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, IdpScimTokenCreate.class), response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponseContent.class),
                                response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponseContent.class),
                                response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponseContent.class),
                                response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponseContent.class),
                                response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MyOrganizationApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new MyOrganizationException("Network error executing HTTP request", e);
        }
    }

    /**
     * Revoke a SCIM token specified by token ID for the Provisioning Configuration of an Identity Provider specified by ID for this Organization.
     */
    public MyOrganizationApiHttpResponse<Void> delete(String idpId, String idpScimTokenId) {
        return delete(idpId, idpScimTokenId, null);
    }

    /**
     * Revoke a SCIM token specified by token ID for the Provisioning Configuration of an Identity Provider specified by ID for this Organization.
     */
    public MyOrganizationApiHttpResponse<Void> delete(
            String idpId, String idpScimTokenId, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("identity-providers")
                .addPathSegment(idpId)
                .addPathSegments("provisioning/scim-tokens")
                .addPathSegment(idpScimTokenId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new MyOrganizationApiHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponseContent.class),
                                response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponseContent.class),
                                response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponseContent.class),
                                response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponseContent.class),
                                response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MyOrganizationApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new MyOrganizationException("Network error executing HTTP request", e);
        }
    }
}
