/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.core;

/**
 * This class serves as the base exception for all errors in the SDK.
 */
public class MyOrganizationException extends RuntimeException {
    public MyOrganizationException(String message) {
        super(message);
    }

    public MyOrganizationException(String message, Exception e) {
        super(message, e);
    }
}
