/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.organization.configuration;

import com.auth0.client.myorganization.core.ClientOptions;
import com.auth0.client.myorganization.core.RequestOptions;
import com.auth0.client.myorganization.types.IdentityProvidersConfig;
import java.util.concurrent.CompletableFuture;

public class AsyncIdentityProvidersClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawIdentityProvidersClient rawClient;

    public AsyncIdentityProvidersClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawIdentityProvidersClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawIdentityProvidersClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieve the <a href="https://auth0.com/docs/authenticate/enterprise-connections/connection-profile">Connection Profile</a> for this application. You should cache this information as it does not change frequently.
     */
    public CompletableFuture<IdentityProvidersConfig> get() {
        return this.rawClient.get().thenApply(response -> response.body());
    }

    /**
     * Retrieve the <a href="https://auth0.com/docs/authenticate/enterprise-connections/connection-profile">Connection Profile</a> for this application. You should cache this information as it does not change frequently.
     */
    public CompletableFuture<IdentityProvidersConfig> get(RequestOptions requestOptions) {
        return this.rawClient.get(requestOptions).thenApply(response -> response.body());
    }
}
