/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.organization.invitations;

import com.auth0.client.myorganization.core.ClientOptions;
import com.auth0.client.myorganization.core.RequestOptions;
import com.auth0.client.myorganization.types.GetMemberInvitationRolesResponseContent;
import java.util.concurrent.CompletableFuture;

public class AsyncRolesClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawRolesClient rawClient;

    public AsyncRolesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawRolesClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawRolesClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieve the roles assigned to a member invitation specified by ID for this Organization.
     */
    public CompletableFuture<GetMemberInvitationRolesResponseContent> list(String invitationId) {
        return this.rawClient.list(invitationId).thenApply(response -> response.body());
    }

    /**
     * Retrieve the roles assigned to a member invitation specified by ID for this Organization.
     */
    public CompletableFuture<GetMemberInvitationRolesResponseContent> list(
            String invitationId, RequestOptions requestOptions) {
        return this.rawClient.list(invitationId, requestOptions).thenApply(response -> response.body());
    }
}
