/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.organization.types;

import com.auth0.client.myorganization.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DeleteMemberInvitationsRequestContent.Builder.class)
public final class DeleteMemberInvitationsRequestContent {
    private final List<String> invitations;

    private final Map<String, Object> additionalProperties;

    private DeleteMemberInvitationsRequestContent(List<String> invitations, Map<String, Object> additionalProperties) {
        this.invitations = invitations;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("invitations")
    public List<String> getInvitations() {
        return invitations;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DeleteMemberInvitationsRequestContent
                && equalTo((DeleteMemberInvitationsRequestContent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DeleteMemberInvitationsRequestContent other) {
        return invitations.equals(other.invitations);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.invitations);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private List<String> invitations = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(DeleteMemberInvitationsRequestContent other) {
            invitations(other.getInvitations());
            return this;
        }

        @JsonSetter(value = "invitations", nulls = Nulls.SKIP)
        public Builder invitations(List<String> invitations) {
            this.invitations.clear();
            if (invitations != null) {
                this.invitations.addAll(invitations);
            }
            return this;
        }

        public Builder addInvitations(String invitations) {
            this.invitations.add(invitations);
            return this;
        }

        public Builder addAllInvitations(List<String> invitations) {
            if (invitations != null) {
                this.invitations.addAll(invitations);
            }
            return this;
        }

        public DeleteMemberInvitationsRequestContent build() {
            return new DeleteMemberInvitationsRequestContent(invitations, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
