/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.organization.members;

import com.auth0.client.myorganization.core.ClientOptions;
import com.auth0.client.myorganization.core.RequestOptions;
import com.auth0.client.myorganization.core.SyncPagingIterable;
import com.auth0.client.myorganization.organization.members.types.ListOrgMemberRolesRequestParameters;
import com.auth0.client.myorganization.types.OrganizationMemberRolesChangeRequestContent;
import com.auth0.client.myorganization.types.Role;
import java.util.concurrent.CompletableFuture;

public class AsyncRolesClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawRolesClient rawClient;

    public AsyncRolesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawRolesClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawRolesClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieve a list of roles assigned to a member specified by ID for this Organization.
     */
    public CompletableFuture<SyncPagingIterable<Role>> list(String userId) {
        return this.rawClient.list(userId).thenApply(response -> response.body());
    }

    /**
     * Retrieve a list of roles assigned to a member specified by ID for this Organization.
     */
    public CompletableFuture<SyncPagingIterable<Role>> list(String userId, RequestOptions requestOptions) {
        return this.rawClient.list(userId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieve a list of roles assigned to a member specified by ID for this Organization.
     */
    public CompletableFuture<SyncPagingIterable<Role>> list(
            String userId, ListOrgMemberRolesRequestParameters request) {
        return this.rawClient.list(userId, request).thenApply(response -> response.body());
    }

    /**
     * Retrieve a list of roles assigned to a member specified by ID for this Organization.
     */
    public CompletableFuture<SyncPagingIterable<Role>> list(
            String userId, ListOrgMemberRolesRequestParameters request, RequestOptions requestOptions) {
        return this.rawClient.list(userId, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Assign roles to a member specified by ID for this Organization.
     */
    public CompletableFuture<Void> assign(String userId, OrganizationMemberRolesChangeRequestContent request) {
        return this.rawClient.assign(userId, request).thenApply(response -> response.body());
    }

    /**
     * Assign roles to a member specified by ID for this Organization.
     */
    public CompletableFuture<Void> assign(
            String userId, OrganizationMemberRolesChangeRequestContent request, RequestOptions requestOptions) {
        return this.rawClient.assign(userId, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Remove roles from a member specified by ID for this Organization.
     */
    public CompletableFuture<Void> unassign(String userId, OrganizationMemberRolesChangeRequestContent request) {
        return this.rawClient.unassign(userId, request).thenApply(response -> response.body());
    }

    /**
     * Remove roles from a member specified by ID for this Organization.
     */
    public CompletableFuture<Void> unassign(
            String userId, OrganizationMemberRolesChangeRequestContent request, RequestOptions requestOptions) {
        return this.rawClient.unassign(userId, request, requestOptions).thenApply(response -> response.body());
    }
}
