/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.auth0.client.myorganization.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Automatic.Builder.class)
public final class Automatic {
    private final Optional<String> metadataUrl;

    private final Optional<Boolean> signSamlRequest;

    private final Optional<IdpSignAlgTypeEnum> signatureAlgorithm;

    private final Optional<IdpSignAlgDigestTypeEnum> digestAlgorithm;

    private final Optional<IdpProtocolBindingTypeEnum> protocolBinding;

    private final Optional<String> bindingMethod;

    private final Optional<String> cert;

    private final Optional<IdpOptionsIdpInitiated> idpInitiated;

    private final Optional<String> iconUrl;

    private final Map<String, Object> additionalProperties;

    private Automatic(
            Optional<String> metadataUrl,
            Optional<Boolean> signSamlRequest,
            Optional<IdpSignAlgTypeEnum> signatureAlgorithm,
            Optional<IdpSignAlgDigestTypeEnum> digestAlgorithm,
            Optional<IdpProtocolBindingTypeEnum> protocolBinding,
            Optional<String> bindingMethod,
            Optional<String> cert,
            Optional<IdpOptionsIdpInitiated> idpInitiated,
            Optional<String> iconUrl,
            Map<String, Object> additionalProperties) {
        this.metadataUrl = metadataUrl;
        this.signSamlRequest = signSamlRequest;
        this.signatureAlgorithm = signatureAlgorithm;
        this.digestAlgorithm = digestAlgorithm;
        this.protocolBinding = protocolBinding;
        this.bindingMethod = bindingMethod;
        this.cert = cert;
        this.idpInitiated = idpInitiated;
        this.iconUrl = iconUrl;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return URL provided by SAML provider which returns information used for creating the connection
     */
    @JsonProperty("metadataUrl")
    public Optional<String> getMetadataUrl() {
        return metadataUrl;
    }

    /**
     * @return When enabled, the SAML authentication request will be signed.
     */
    @JsonProperty("signSAMLRequest")
    public Optional<Boolean> getSignSamlRequest() {
        return signSamlRequest;
    }

    @JsonProperty("signatureAlgorithm")
    public Optional<IdpSignAlgTypeEnum> getSignatureAlgorithm() {
        return signatureAlgorithm;
    }

    @JsonProperty("digestAlgorithm")
    public Optional<IdpSignAlgDigestTypeEnum> getDigestAlgorithm() {
        return digestAlgorithm;
    }

    @JsonProperty("protocolBinding")
    public Optional<IdpProtocolBindingTypeEnum> getProtocolBinding() {
        return protocolBinding;
    }

    /**
     * @return Defines the specific HTTP binding used for sending SAML messages.
     */
    @JsonProperty("bindingMethod")
    public Optional<String> getBindingMethod() {
        return bindingMethod;
    }

    /**
     * @return Signing certificate (encoded in PEM or CER) you retrieved from the IdP
     */
    @JsonProperty("cert")
    public Optional<String> getCert() {
        return cert;
    }

    @JsonProperty("idpInitiated")
    public Optional<IdpOptionsIdpInitiated> getIdpInitiated() {
        return idpInitiated;
    }

    /**
     * @return A URL pointing to an image file that represents your client application.
     */
    @JsonProperty("icon_url")
    public Optional<String> getIconUrl() {
        return iconUrl;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof Automatic && equalTo((Automatic) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(Automatic other) {
        return metadataUrl.equals(other.metadataUrl)
                && signSamlRequest.equals(other.signSamlRequest)
                && signatureAlgorithm.equals(other.signatureAlgorithm)
                && digestAlgorithm.equals(other.digestAlgorithm)
                && protocolBinding.equals(other.protocolBinding)
                && bindingMethod.equals(other.bindingMethod)
                && cert.equals(other.cert)
                && idpInitiated.equals(other.idpInitiated)
                && iconUrl.equals(other.iconUrl);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.metadataUrl,
                this.signSamlRequest,
                this.signatureAlgorithm,
                this.digestAlgorithm,
                this.protocolBinding,
                this.bindingMethod,
                this.cert,
                this.idpInitiated,
                this.iconUrl);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> metadataUrl = Optional.empty();

        private Optional<Boolean> signSamlRequest = Optional.empty();

        private Optional<IdpSignAlgTypeEnum> signatureAlgorithm = Optional.empty();

        private Optional<IdpSignAlgDigestTypeEnum> digestAlgorithm = Optional.empty();

        private Optional<IdpProtocolBindingTypeEnum> protocolBinding = Optional.empty();

        private Optional<String> bindingMethod = Optional.empty();

        private Optional<String> cert = Optional.empty();

        private Optional<IdpOptionsIdpInitiated> idpInitiated = Optional.empty();

        private Optional<String> iconUrl = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(Automatic other) {
            metadataUrl(other.getMetadataUrl());
            signSamlRequest(other.getSignSamlRequest());
            signatureAlgorithm(other.getSignatureAlgorithm());
            digestAlgorithm(other.getDigestAlgorithm());
            protocolBinding(other.getProtocolBinding());
            bindingMethod(other.getBindingMethod());
            cert(other.getCert());
            idpInitiated(other.getIdpInitiated());
            iconUrl(other.getIconUrl());
            return this;
        }

        /**
         * <p>URL provided by SAML provider which returns information used for creating the connection</p>
         */
        @JsonSetter(value = "metadataUrl", nulls = Nulls.SKIP)
        public Builder metadataUrl(Optional<String> metadataUrl) {
            this.metadataUrl = metadataUrl;
            return this;
        }

        public Builder metadataUrl(String metadataUrl) {
            this.metadataUrl = Optional.ofNullable(metadataUrl);
            return this;
        }

        /**
         * <p>When enabled, the SAML authentication request will be signed.</p>
         */
        @JsonSetter(value = "signSAMLRequest", nulls = Nulls.SKIP)
        public Builder signSamlRequest(Optional<Boolean> signSamlRequest) {
            this.signSamlRequest = signSamlRequest;
            return this;
        }

        public Builder signSamlRequest(Boolean signSamlRequest) {
            this.signSamlRequest = Optional.ofNullable(signSamlRequest);
            return this;
        }

        @JsonSetter(value = "signatureAlgorithm", nulls = Nulls.SKIP)
        public Builder signatureAlgorithm(Optional<IdpSignAlgTypeEnum> signatureAlgorithm) {
            this.signatureAlgorithm = signatureAlgorithm;
            return this;
        }

        public Builder signatureAlgorithm(IdpSignAlgTypeEnum signatureAlgorithm) {
            this.signatureAlgorithm = Optional.ofNullable(signatureAlgorithm);
            return this;
        }

        @JsonSetter(value = "digestAlgorithm", nulls = Nulls.SKIP)
        public Builder digestAlgorithm(Optional<IdpSignAlgDigestTypeEnum> digestAlgorithm) {
            this.digestAlgorithm = digestAlgorithm;
            return this;
        }

        public Builder digestAlgorithm(IdpSignAlgDigestTypeEnum digestAlgorithm) {
            this.digestAlgorithm = Optional.ofNullable(digestAlgorithm);
            return this;
        }

        @JsonSetter(value = "protocolBinding", nulls = Nulls.SKIP)
        public Builder protocolBinding(Optional<IdpProtocolBindingTypeEnum> protocolBinding) {
            this.protocolBinding = protocolBinding;
            return this;
        }

        public Builder protocolBinding(IdpProtocolBindingTypeEnum protocolBinding) {
            this.protocolBinding = Optional.ofNullable(protocolBinding);
            return this;
        }

        /**
         * <p>Defines the specific HTTP binding used for sending SAML messages.</p>
         */
        @JsonSetter(value = "bindingMethod", nulls = Nulls.SKIP)
        public Builder bindingMethod(Optional<String> bindingMethod) {
            this.bindingMethod = bindingMethod;
            return this;
        }

        public Builder bindingMethod(String bindingMethod) {
            this.bindingMethod = Optional.ofNullable(bindingMethod);
            return this;
        }

        /**
         * <p>Signing certificate (encoded in PEM or CER) you retrieved from the IdP</p>
         */
        @JsonSetter(value = "cert", nulls = Nulls.SKIP)
        public Builder cert(Optional<String> cert) {
            this.cert = cert;
            return this;
        }

        public Builder cert(String cert) {
            this.cert = Optional.ofNullable(cert);
            return this;
        }

        @JsonSetter(value = "idpInitiated", nulls = Nulls.SKIP)
        public Builder idpInitiated(Optional<IdpOptionsIdpInitiated> idpInitiated) {
            this.idpInitiated = idpInitiated;
            return this;
        }

        public Builder idpInitiated(IdpOptionsIdpInitiated idpInitiated) {
            this.idpInitiated = Optional.ofNullable(idpInitiated);
            return this;
        }

        /**
         * <p>A URL pointing to an image file that represents your client application.</p>
         */
        @JsonSetter(value = "icon_url", nulls = Nulls.SKIP)
        public Builder iconUrl(Optional<String> iconUrl) {
            this.iconUrl = iconUrl;
            return this;
        }

        public Builder iconUrl(String iconUrl) {
            this.iconUrl = Optional.ofNullable(iconUrl);
            return this;
        }

        public Automatic build() {
            return new Automatic(
                    metadataUrl,
                    signSamlRequest,
                    signatureAlgorithm,
                    digestAlgorithm,
                    protocolBinding,
                    bindingMethod,
                    cert,
                    idpInitiated,
                    iconUrl,
                    additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
