/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.auth0.client.myorganization.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import java.io.IOException;
import java.util.Objects;

@JsonDeserialize(using = BadRequestErrorBody.Deserializer.class)
public final class BadRequestErrorBody {
    private final Object value;

    private final int type;

    private BadRequestErrorBody(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    @SuppressWarnings("unchecked")
    public <T> T visit(Visitor<T> visitor) {
        if (this.type == 0) {
            return visitor.visit((ErrorResponseContent) this.value);
        } else if (this.type == 1) {
            return visitor.visit((ValidationErrorResponseContent) this.value);
        }
        throw new IllegalStateException("Failed to visit value. This should never happen.");
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof BadRequestErrorBody && equalTo((BadRequestErrorBody) other);
    }

    private boolean equalTo(BadRequestErrorBody other) {
        return value.equals(other.value);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.value);
    }

    @Override
    public String toString() {
        return this.value.toString();
    }

    public static BadRequestErrorBody of(ErrorResponseContent value) {
        return new BadRequestErrorBody(value, 0);
    }

    public static BadRequestErrorBody of(ValidationErrorResponseContent value) {
        return new BadRequestErrorBody(value, 1);
    }

    public interface Visitor<T> {
        T visit(ErrorResponseContent value);

        T visit(ValidationErrorResponseContent value);
    }

    static final class Deserializer extends StdDeserializer<BadRequestErrorBody> {
        Deserializer() {
            super(BadRequestErrorBody.class);
        }

        @Override
        public BadRequestErrorBody deserialize(JsonParser p, DeserializationContext context) throws IOException {
            Object value = p.readValueAs(Object.class);
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, ErrorResponseContent.class));
            } catch (RuntimeException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, ValidationErrorResponseContent.class));
            } catch (RuntimeException e) {
            }
            throw new JsonParseException(p, "Failed to deserialize");
        }
    }
}
