/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.auth0.client.myorganization.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CrossAppAccessResourceAppConfig.Builder.class)
public final class CrossAppAccessResourceAppConfig {
    private final CrossAppAccessResourceAppStatusConfig status;

    private final Map<String, Object> additionalProperties;

    private CrossAppAccessResourceAppConfig(
            CrossAppAccessResourceAppStatusConfig status, Map<String, Object> additionalProperties) {
        this.status = status;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("status")
    public CrossAppAccessResourceAppStatusConfig getStatus() {
        return status;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CrossAppAccessResourceAppConfig && equalTo((CrossAppAccessResourceAppConfig) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CrossAppAccessResourceAppConfig other) {
        return status.equals(other.status);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.status);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static StatusStage builder() {
        return new Builder();
    }

    public interface StatusStage {
        _FinalStage status(@NotNull CrossAppAccessResourceAppStatusConfig status);

        Builder from(CrossAppAccessResourceAppConfig other);
    }

    public interface _FinalStage {
        CrossAppAccessResourceAppConfig build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements StatusStage, _FinalStage {
        private CrossAppAccessResourceAppStatusConfig status;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CrossAppAccessResourceAppConfig other) {
            status(other.getStatus());
            return this;
        }

        @java.lang.Override
        @JsonSetter("status")
        public _FinalStage status(@NotNull CrossAppAccessResourceAppStatusConfig status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        @java.lang.Override
        public CrossAppAccessResourceAppConfig build() {
            return new CrossAppAccessResourceAppConfig(status, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
