/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.auth0.client.myorganization.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ErrorResponseContent.Builder.class)
public final class ErrorResponseContent {
    private final String type;

    private final int status;

    private final String title;

    private final String detail;

    private final Map<String, Object> additionalProperties;

    private ErrorResponseContent(
            String type, int status, String title, String detail, Map<String, Object> additionalProperties) {
        this.type = type;
        this.status = status;
        this.title = title;
        this.detail = detail;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return A URI that describes the error.
     */
    @JsonProperty("type")
    public String getType() {
        return type;
    }

    /**
     * @return The HTTP status code result of the request.
     */
    @JsonProperty("status")
    public int getStatus() {
        return status;
    }

    /**
     * @return A brief description of the error.
     */
    @JsonProperty("title")
    public String getTitle() {
        return title;
    }

    /**
     * @return A detailed description of the error.
     */
    @JsonProperty("detail")
    public String getDetail() {
        return detail;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ErrorResponseContent && equalTo((ErrorResponseContent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ErrorResponseContent other) {
        return type.equals(other.type)
                && status == other.status
                && title.equals(other.title)
                && detail.equals(other.detail);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.type, this.status, this.title, this.detail);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TypeStage builder() {
        return new Builder();
    }

    public interface TypeStage {
        /**
         * <p>A URI that describes the error.</p>
         */
        StatusStage type(@NotNull String type);

        Builder from(ErrorResponseContent other);
    }

    public interface StatusStage {
        /**
         * <p>The HTTP status code result of the request.</p>
         */
        TitleStage status(int status);
    }

    public interface TitleStage {
        /**
         * <p>A brief description of the error.</p>
         */
        DetailStage title(@NotNull String title);
    }

    public interface DetailStage {
        /**
         * <p>A detailed description of the error.</p>
         */
        _FinalStage detail(@NotNull String detail);
    }

    public interface _FinalStage {
        ErrorResponseContent build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TypeStage, StatusStage, TitleStage, DetailStage, _FinalStage {
        private String type;

        private int status;

        private String title;

        private String detail;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ErrorResponseContent other) {
            type(other.getType());
            status(other.getStatus());
            title(other.getTitle());
            detail(other.getDetail());
            return this;
        }

        /**
         * <p>A URI that describes the error.</p>
         * <p>A URI that describes the error.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("type")
        public StatusStage type(@NotNull String type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        /**
         * <p>The HTTP status code result of the request.</p>
         * <p>The HTTP status code result of the request.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("status")
        public TitleStage status(int status) {
            this.status = status;
            return this;
        }

        /**
         * <p>A brief description of the error.</p>
         * <p>A brief description of the error.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("title")
        public DetailStage title(@NotNull String title) {
            this.title = Objects.requireNonNull(title, "title must not be null");
            return this;
        }

        /**
         * <p>A detailed description of the error.</p>
         * <p>A detailed description of the error.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("detail")
        public _FinalStage detail(@NotNull String detail) {
            this.detail = Objects.requireNonNull(detail, "detail must not be null");
            return this;
        }

        @java.lang.Override
        public ErrorResponseContent build() {
            return new ErrorResponseContent(type, status, title, detail, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
