/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.auth0.client.myorganization.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FedMetadataXml.Builder.class)
public final class FedMetadataXml {
    private final Optional<String> fedMetadataXml;

    private final Map<String, Object> additionalProperties;

    private FedMetadataXml(Optional<String> fedMetadataXml, Map<String, Object> additionalProperties) {
        this.fedMetadataXml = fedMetadataXml;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return A Federation Metadata XML file in ADFS is a crucial document that serves as a blueprint for establishing trust between an ADFS server and other relying parties that want to consume identity information from ADFS.
     */
    @JsonProperty("fedMetadataXml")
    public Optional<String> getFedMetadataXml() {
        return fedMetadataXml;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof FedMetadataXml && equalTo((FedMetadataXml) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(FedMetadataXml other) {
        return fedMetadataXml.equals(other.fedMetadataXml);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.fedMetadataXml);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> fedMetadataXml = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(FedMetadataXml other) {
            fedMetadataXml(other.getFedMetadataXml());
            return this;
        }

        /**
         * <p>A Federation Metadata XML file in ADFS is a crucial document that serves as a blueprint for establishing trust between an ADFS server and other relying parties that want to consume identity information from ADFS.</p>
         */
        @JsonSetter(value = "fedMetadataXml", nulls = Nulls.SKIP)
        public Builder fedMetadataXml(Optional<String> fedMetadataXml) {
            this.fedMetadataXml = fedMetadataXml;
            return this;
        }

        public Builder fedMetadataXml(String fedMetadataXml) {
            this.fedMetadataXml = Optional.ofNullable(fedMetadataXml);
            return this;
        }

        public FedMetadataXml build() {
            return new FedMetadataXml(fedMetadataXml, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
