/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.auth0.client.myorganization.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetConfigurationResponseContent.Builder.class)
public final class GetConfigurationResponseContent {
    private final Optional<List<IdpStrategyEnum>> allowedStrategies;

    private final Optional<IdpConnectionDeletionBehaviorEnum> connectionDeletionBehavior;

    private final Map<String, Object> additionalProperties;

    private GetConfigurationResponseContent(
            Optional<List<IdpStrategyEnum>> allowedStrategies,
            Optional<IdpConnectionDeletionBehaviorEnum> connectionDeletionBehavior,
            Map<String, Object> additionalProperties) {
        this.allowedStrategies = allowedStrategies;
        this.connectionDeletionBehavior = connectionDeletionBehavior;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Array of supported strategies
     */
    @JsonProperty("allowed_strategies")
    public Optional<List<IdpStrategyEnum>> getAllowedStrategies() {
        return allowedStrategies;
    }

    @JsonProperty("connection_deletion_behavior")
    public Optional<IdpConnectionDeletionBehaviorEnum> getConnectionDeletionBehavior() {
        return connectionDeletionBehavior;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GetConfigurationResponseContent && equalTo((GetConfigurationResponseContent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GetConfigurationResponseContent other) {
        return allowedStrategies.equals(other.allowedStrategies)
                && connectionDeletionBehavior.equals(other.connectionDeletionBehavior);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.allowedStrategies, this.connectionDeletionBehavior);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<IdpStrategyEnum>> allowedStrategies = Optional.empty();

        private Optional<IdpConnectionDeletionBehaviorEnum> connectionDeletionBehavior = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(GetConfigurationResponseContent other) {
            allowedStrategies(other.getAllowedStrategies());
            connectionDeletionBehavior(other.getConnectionDeletionBehavior());
            return this;
        }

        /**
         * <p>Array of supported strategies</p>
         */
        @JsonSetter(value = "allowed_strategies", nulls = Nulls.SKIP)
        public Builder allowedStrategies(Optional<List<IdpStrategyEnum>> allowedStrategies) {
            this.allowedStrategies = allowedStrategies;
            return this;
        }

        public Builder allowedStrategies(List<IdpStrategyEnum> allowedStrategies) {
            this.allowedStrategies = Optional.ofNullable(allowedStrategies);
            return this;
        }

        @JsonSetter(value = "connection_deletion_behavior", nulls = Nulls.SKIP)
        public Builder connectionDeletionBehavior(
                Optional<IdpConnectionDeletionBehaviorEnum> connectionDeletionBehavior) {
            this.connectionDeletionBehavior = connectionDeletionBehavior;
            return this;
        }

        public Builder connectionDeletionBehavior(IdpConnectionDeletionBehaviorEnum connectionDeletionBehavior) {
            this.connectionDeletionBehavior = Optional.ofNullable(connectionDeletionBehavior);
            return this;
        }

        public GetConfigurationResponseContent build() {
            return new GetConfigurationResponseContent(
                    allowedStrategies, connectionDeletionBehavior, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
