/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.auth0.client.myorganization.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetMemberInvitationRolesResponseContent.Builder.class)
public final class GetMemberInvitationRolesResponseContent {
    private final List<Role> roles;

    private final Map<String, Object> additionalProperties;

    private GetMemberInvitationRolesResponseContent(List<Role> roles, Map<String, Object> additionalProperties) {
        this.roles = roles;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("roles")
    public List<Role> getRoles() {
        return roles;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GetMemberInvitationRolesResponseContent
                && equalTo((GetMemberInvitationRolesResponseContent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GetMemberInvitationRolesResponseContent other) {
        return roles.equals(other.roles);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.roles);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private List<Role> roles = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(GetMemberInvitationRolesResponseContent other) {
            roles(other.getRoles());
            return this;
        }

        @JsonSetter(value = "roles", nulls = Nulls.SKIP)
        public Builder roles(List<Role> roles) {
            this.roles.clear();
            if (roles != null) {
                this.roles.addAll(roles);
            }
            return this;
        }

        public Builder addRoles(Role roles) {
            this.roles.add(roles);
            return this;
        }

        public Builder addAllRoles(List<Role> roles) {
            if (roles != null) {
                this.roles.addAll(roles);
            }
            return this;
        }

        public GetMemberInvitationRolesResponseContent build() {
            return new GetMemberInvitationRolesResponseContent(roles, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
