/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import java.util.Optional;

public interface IBaseUserAttributeMapItem {
    Optional<String> getUserAttribute();

    Optional<String> getDescription();

    Optional<String> getLabel();

    boolean getIsRequired();

    boolean getIsExtra();

    boolean getIsMissing();
}
