/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class IdentityProvidersConfigEnabledFeaturesEnum {
    public static final IdentityProvidersConfigEnabledFeaturesEnum PROVISIONING =
            new IdentityProvidersConfigEnabledFeaturesEnum(Value.PROVISIONING, "provisioning");

    public static final IdentityProvidersConfigEnabledFeaturesEnum UNIVERSAL_LOGOUT =
            new IdentityProvidersConfigEnabledFeaturesEnum(Value.UNIVERSAL_LOGOUT, "universal_logout");

    private final Value value;

    private final String string;

    IdentityProvidersConfigEnabledFeaturesEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof IdentityProvidersConfigEnabledFeaturesEnum
                        && this.string.equals(((IdentityProvidersConfigEnabledFeaturesEnum) other).string));
    }

    @Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case PROVISIONING:
                return visitor.visitProvisioning();
            case UNIVERSAL_LOGOUT:
                return visitor.visitUniversalLogout();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static IdentityProvidersConfigEnabledFeaturesEnum valueOf(String value) {
        switch (value) {
            case "provisioning":
                return PROVISIONING;
            case "universal_logout":
                return UNIVERSAL_LOGOUT;
            default:
                return new IdentityProvidersConfigEnabledFeaturesEnum(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        PROVISIONING,

        UNIVERSAL_LOGOUT,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitProvisioning();

        T visitUniversalLogout();

        T visitUnknown(String unknownType);
    }
}
