/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.auth0.client.myorganization.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = IdentityProvidersConfigStrategyOverride.Builder.class)
public final class IdentityProvidersConfigStrategyOverride {
    private final Optional<IdentityProvidersConfigStrategyBase> adfs;

    private final Optional<IdentityProvidersConfigStrategyBase> googleapps;

    private final Optional<IdentityProvidersConfigStrategyBase> oidc;

    private final Optional<IdentityProvidersConfigStrategyBase> okta;

    private final Optional<IdentityProvidersConfigStrategyBase> pingfederate;

    private final Optional<IdentityProvidersConfigStrategyBase> samlp;

    private final Optional<IdentityProvidersConfigStrategyBase> waad;

    private final Map<String, Object> additionalProperties;

    private IdentityProvidersConfigStrategyOverride(
            Optional<IdentityProvidersConfigStrategyBase> adfs,
            Optional<IdentityProvidersConfigStrategyBase> googleapps,
            Optional<IdentityProvidersConfigStrategyBase> oidc,
            Optional<IdentityProvidersConfigStrategyBase> okta,
            Optional<IdentityProvidersConfigStrategyBase> pingfederate,
            Optional<IdentityProvidersConfigStrategyBase> samlp,
            Optional<IdentityProvidersConfigStrategyBase> waad,
            Map<String, Object> additionalProperties) {
        this.adfs = adfs;
        this.googleapps = googleapps;
        this.oidc = oidc;
        this.okta = okta;
        this.pingfederate = pingfederate;
        this.samlp = samlp;
        this.waad = waad;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("adfs")
    public Optional<IdentityProvidersConfigStrategyBase> getAdfs() {
        return adfs;
    }

    @JsonProperty("googleapps")
    public Optional<IdentityProvidersConfigStrategyBase> getGoogleapps() {
        return googleapps;
    }

    @JsonProperty("oidc")
    public Optional<IdentityProvidersConfigStrategyBase> getOidc() {
        return oidc;
    }

    @JsonProperty("okta")
    public Optional<IdentityProvidersConfigStrategyBase> getOkta() {
        return okta;
    }

    @JsonProperty("pingfederate")
    public Optional<IdentityProvidersConfigStrategyBase> getPingfederate() {
        return pingfederate;
    }

    @JsonProperty("samlp")
    public Optional<IdentityProvidersConfigStrategyBase> getSamlp() {
        return samlp;
    }

    @JsonProperty("waad")
    public Optional<IdentityProvidersConfigStrategyBase> getWaad() {
        return waad;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof IdentityProvidersConfigStrategyOverride
                && equalTo((IdentityProvidersConfigStrategyOverride) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(IdentityProvidersConfigStrategyOverride other) {
        return adfs.equals(other.adfs)
                && googleapps.equals(other.googleapps)
                && oidc.equals(other.oidc)
                && okta.equals(other.okta)
                && pingfederate.equals(other.pingfederate)
                && samlp.equals(other.samlp)
                && waad.equals(other.waad);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.adfs, this.googleapps, this.oidc, this.okta, this.pingfederate, this.samlp, this.waad);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<IdentityProvidersConfigStrategyBase> adfs = Optional.empty();

        private Optional<IdentityProvidersConfigStrategyBase> googleapps = Optional.empty();

        private Optional<IdentityProvidersConfigStrategyBase> oidc = Optional.empty();

        private Optional<IdentityProvidersConfigStrategyBase> okta = Optional.empty();

        private Optional<IdentityProvidersConfigStrategyBase> pingfederate = Optional.empty();

        private Optional<IdentityProvidersConfigStrategyBase> samlp = Optional.empty();

        private Optional<IdentityProvidersConfigStrategyBase> waad = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(IdentityProvidersConfigStrategyOverride other) {
            adfs(other.getAdfs());
            googleapps(other.getGoogleapps());
            oidc(other.getOidc());
            okta(other.getOkta());
            pingfederate(other.getPingfederate());
            samlp(other.getSamlp());
            waad(other.getWaad());
            return this;
        }

        @JsonSetter(value = "adfs", nulls = Nulls.SKIP)
        public Builder adfs(Optional<IdentityProvidersConfigStrategyBase> adfs) {
            this.adfs = adfs;
            return this;
        }

        public Builder adfs(IdentityProvidersConfigStrategyBase adfs) {
            this.adfs = Optional.ofNullable(adfs);
            return this;
        }

        @JsonSetter(value = "googleapps", nulls = Nulls.SKIP)
        public Builder googleapps(Optional<IdentityProvidersConfigStrategyBase> googleapps) {
            this.googleapps = googleapps;
            return this;
        }

        public Builder googleapps(IdentityProvidersConfigStrategyBase googleapps) {
            this.googleapps = Optional.ofNullable(googleapps);
            return this;
        }

        @JsonSetter(value = "oidc", nulls = Nulls.SKIP)
        public Builder oidc(Optional<IdentityProvidersConfigStrategyBase> oidc) {
            this.oidc = oidc;
            return this;
        }

        public Builder oidc(IdentityProvidersConfigStrategyBase oidc) {
            this.oidc = Optional.ofNullable(oidc);
            return this;
        }

        @JsonSetter(value = "okta", nulls = Nulls.SKIP)
        public Builder okta(Optional<IdentityProvidersConfigStrategyBase> okta) {
            this.okta = okta;
            return this;
        }

        public Builder okta(IdentityProvidersConfigStrategyBase okta) {
            this.okta = Optional.ofNullable(okta);
            return this;
        }

        @JsonSetter(value = "pingfederate", nulls = Nulls.SKIP)
        public Builder pingfederate(Optional<IdentityProvidersConfigStrategyBase> pingfederate) {
            this.pingfederate = pingfederate;
            return this;
        }

        public Builder pingfederate(IdentityProvidersConfigStrategyBase pingfederate) {
            this.pingfederate = Optional.ofNullable(pingfederate);
            return this;
        }

        @JsonSetter(value = "samlp", nulls = Nulls.SKIP)
        public Builder samlp(Optional<IdentityProvidersConfigStrategyBase> samlp) {
            this.samlp = samlp;
            return this;
        }

        public Builder samlp(IdentityProvidersConfigStrategyBase samlp) {
            this.samlp = Optional.ofNullable(samlp);
            return this;
        }

        @JsonSetter(value = "waad", nulls = Nulls.SKIP)
        public Builder waad(Optional<IdentityProvidersConfigStrategyBase> waad) {
            this.waad = waad;
            return this;
        }

        public Builder waad(IdentityProvidersConfigStrategyBase waad) {
            this.waad = Optional.ofNullable(waad);
            return this;
        }

        public IdentityProvidersConfigStrategyOverride build() {
            return new IdentityProvidersConfigStrategyOverride(
                    adfs, googleapps, oidc, okta, pingfederate, samlp, waad, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
