/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.auth0.client.myorganization.core.NullableNonemptyFilter;
import com.auth0.client.myorganization.core.ObjectMappers;
import com.auth0.client.myorganization.core.OptionalNullable;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.Nullable;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = IdentityProvidersConfigProvisioningConfiguration.Builder.class)
public final class IdentityProvidersConfigProvisioningConfiguration {
    private final Optional<IdentityProvidersConfigProvisioningConfigurationOnLogin> onLogin;

    private final OptionalNullable<IdentityProvidersConfigProvisioningConfigurationScim> scim;

    private final Map<String, Object> additionalProperties;

    private IdentityProvidersConfigProvisioningConfiguration(
            Optional<IdentityProvidersConfigProvisioningConfigurationOnLogin> onLogin,
            OptionalNullable<IdentityProvidersConfigProvisioningConfigurationScim> scim,
            Map<String, Object> additionalProperties) {
        this.onLogin = onLogin;
        this.scim = scim;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("on_login")
    public Optional<IdentityProvidersConfigProvisioningConfigurationOnLogin> getOnLogin() {
        return onLogin;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("scim")
    public OptionalNullable<IdentityProvidersConfigProvisioningConfigurationScim> getScim() {
        if (scim == null) {
            return OptionalNullable.absent();
        }
        return scim;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("scim")
    private OptionalNullable<IdentityProvidersConfigProvisioningConfigurationScim> _getScim() {
        return scim;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof IdentityProvidersConfigProvisioningConfiguration
                && equalTo((IdentityProvidersConfigProvisioningConfiguration) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(IdentityProvidersConfigProvisioningConfiguration other) {
        return onLogin.equals(other.onLogin) && scim.equals(other.scim);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.onLogin, this.scim);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<IdentityProvidersConfigProvisioningConfigurationOnLogin> onLogin = Optional.empty();

        private OptionalNullable<IdentityProvidersConfigProvisioningConfigurationScim> scim = OptionalNullable.absent();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(IdentityProvidersConfigProvisioningConfiguration other) {
            onLogin(other.getOnLogin());
            scim(other.getScim());
            return this;
        }

        @JsonSetter(value = "on_login", nulls = Nulls.SKIP)
        public Builder onLogin(Optional<IdentityProvidersConfigProvisioningConfigurationOnLogin> onLogin) {
            this.onLogin = onLogin;
            return this;
        }

        public Builder onLogin(IdentityProvidersConfigProvisioningConfigurationOnLogin onLogin) {
            this.onLogin = Optional.ofNullable(onLogin);
            return this;
        }

        @JsonSetter(value = "scim", nulls = Nulls.SKIP)
        public Builder scim(@Nullable OptionalNullable<IdentityProvidersConfigProvisioningConfigurationScim> scim) {
            this.scim = scim;
            return this;
        }

        public Builder scim(IdentityProvidersConfigProvisioningConfigurationScim scim) {
            this.scim = OptionalNullable.of(scim);
            return this;
        }

        public Builder scim(Optional<IdentityProvidersConfigProvisioningConfigurationScim> scim) {
            if (scim.isPresent()) {
                this.scim = OptionalNullable.of(scim.get());
            } else {
                this.scim = OptionalNullable.absent();
            }
            return this;
        }

        public Builder scim(
                com.auth0.client.myorganization.core.Nullable<IdentityProvidersConfigProvisioningConfigurationScim>
                        scim) {
            if (scim.isNull()) {
                this.scim = OptionalNullable.ofNull();
            } else if (scim.isEmpty()) {
                this.scim = OptionalNullable.absent();
            } else {
                this.scim = OptionalNullable.of(scim.get());
            }
            return this;
        }

        public IdentityProvidersConfigProvisioningConfiguration build() {
            return new IdentityProvidersConfigProvisioningConfiguration(onLogin, scim, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
