/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.auth0.client.myorganization.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = IdentityProvidersConfigOrganization.Builder.class)
public final class IdentityProvidersConfigOrganization {
    private final boolean canSetShowAsButton;

    private final boolean canSetAssignMembershipOnLogin;

    private final Map<String, Object> additionalProperties;

    private IdentityProvidersConfigOrganization(
            boolean canSetShowAsButton,
            boolean canSetAssignMembershipOnLogin,
            Map<String, Object> additionalProperties) {
        this.canSetShowAsButton = canSetShowAsButton;
        this.canSetAssignMembershipOnLogin = canSetAssignMembershipOnLogin;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return If Org Admin can set show_as_button
     */
    @JsonProperty("can_set_show_as_button")
    public boolean getCanSetShowAsButton() {
        return canSetShowAsButton;
    }

    /**
     * @return If Org Admin can set assign_membership_on_login
     */
    @JsonProperty("can_set_assign_membership_on_login")
    public boolean getCanSetAssignMembershipOnLogin() {
        return canSetAssignMembershipOnLogin;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof IdentityProvidersConfigOrganization
                && equalTo((IdentityProvidersConfigOrganization) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(IdentityProvidersConfigOrganization other) {
        return canSetShowAsButton == other.canSetShowAsButton
                && canSetAssignMembershipOnLogin == other.canSetAssignMembershipOnLogin;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.canSetShowAsButton, this.canSetAssignMembershipOnLogin);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CanSetShowAsButtonStage builder() {
        return new Builder();
    }

    public interface CanSetShowAsButtonStage {
        /**
         * <p>If Org Admin can set show_as_button</p>
         */
        CanSetAssignMembershipOnLoginStage canSetShowAsButton(boolean canSetShowAsButton);

        Builder from(IdentityProvidersConfigOrganization other);
    }

    public interface CanSetAssignMembershipOnLoginStage {
        /**
         * <p>If Org Admin can set assign_membership_on_login</p>
         */
        _FinalStage canSetAssignMembershipOnLogin(boolean canSetAssignMembershipOnLogin);
    }

    public interface _FinalStage {
        IdentityProvidersConfigOrganization build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements CanSetShowAsButtonStage, CanSetAssignMembershipOnLoginStage, _FinalStage {
        private boolean canSetShowAsButton;

        private boolean canSetAssignMembershipOnLogin;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(IdentityProvidersConfigOrganization other) {
            canSetShowAsButton(other.getCanSetShowAsButton());
            canSetAssignMembershipOnLogin(other.getCanSetAssignMembershipOnLogin());
            return this;
        }

        /**
         * <p>If Org Admin can set show_as_button</p>
         * <p>If Org Admin can set show_as_button</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("can_set_show_as_button")
        public CanSetAssignMembershipOnLoginStage canSetShowAsButton(boolean canSetShowAsButton) {
            this.canSetShowAsButton = canSetShowAsButton;
            return this;
        }

        /**
         * <p>If Org Admin can set assign_membership_on_login</p>
         * <p>If Org Admin can set assign_membership_on_login</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("can_set_assign_membership_on_login")
        public _FinalStage canSetAssignMembershipOnLogin(boolean canSetAssignMembershipOnLogin) {
            this.canSetAssignMembershipOnLogin = canSetAssignMembershipOnLogin;
            return this;
        }

        @java.lang.Override
        public IdentityProvidersConfigOrganization build() {
            return new IdentityProvidersConfigOrganization(
                    canSetShowAsButton, canSetAssignMembershipOnLogin, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
