/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.auth0.client.myorganization.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = IdentityProvidersConfigProvisioningConfigurationScim.Builder.class)
public final class IdentityProvidersConfigProvisioningConfigurationScim {
    private final IdentityProvidersConfigProvisioningConfigurationScimTokens tokens;

    private final Map<String, Object> additionalProperties;

    private IdentityProvidersConfigProvisioningConfigurationScim(
            IdentityProvidersConfigProvisioningConfigurationScimTokens tokens,
            Map<String, Object> additionalProperties) {
        this.tokens = tokens;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("tokens")
    public IdentityProvidersConfigProvisioningConfigurationScimTokens getTokens() {
        return tokens;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof IdentityProvidersConfigProvisioningConfigurationScim
                && equalTo((IdentityProvidersConfigProvisioningConfigurationScim) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(IdentityProvidersConfigProvisioningConfigurationScim other) {
        return tokens.equals(other.tokens);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.tokens);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TokensStage builder() {
        return new Builder();
    }

    public interface TokensStage {
        _FinalStage tokens(@NotNull IdentityProvidersConfigProvisioningConfigurationScimTokens tokens);

        Builder from(IdentityProvidersConfigProvisioningConfigurationScim other);
    }

    public interface _FinalStage {
        IdentityProvidersConfigProvisioningConfigurationScim build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TokensStage, _FinalStage {
        private IdentityProvidersConfigProvisioningConfigurationScimTokens tokens;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(IdentityProvidersConfigProvisioningConfigurationScim other) {
            tokens(other.getTokens());
            return this;
        }

        @java.lang.Override
        @JsonSetter("tokens")
        public _FinalStage tokens(@NotNull IdentityProvidersConfigProvisioningConfigurationScimTokens tokens) {
            this.tokens = Objects.requireNonNull(tokens, "tokens must not be null");
            return this;
        }

        @java.lang.Override
        public IdentityProvidersConfigProvisioningConfigurationScim build() {
            return new IdentityProvidersConfigProvisioningConfigurationScim(tokens, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
