/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class IdpAdfsResponseStrategy {
    public static final IdpAdfsResponseStrategy ADFS = new IdpAdfsResponseStrategy(Value.ADFS, "adfs");

    private final Value value;

    private final String string;

    IdpAdfsResponseStrategy(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof IdpAdfsResponseStrategy
                        && this.string.equals(((IdpAdfsResponseStrategy) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case ADFS:
                return visitor.visitAdfs();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static IdpAdfsResponseStrategy valueOf(String value) {
        switch (value) {
            case "adfs":
                return ADFS;
            default:
                return new IdpAdfsResponseStrategy(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ADFS,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitAdfs();

        T visitUnknown(String unknownType);
    }
}
