/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.auth0.client.myorganization.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = IdpGoogleAppsUpdateRequest.Builder.class)
public final class IdpGoogleAppsUpdateRequest implements IIdpUpdateBase {
    private final Optional<String> displayName;

    private final Optional<Boolean> showAsButton;

    private final Optional<Boolean> assignMembershipOnLogin;

    private final Optional<Boolean> isEnabled;

    private final Optional<IdpGoogleAppsOptionsRequest> options;

    private final Map<String, Object> additionalProperties;

    private IdpGoogleAppsUpdateRequest(
            Optional<String> displayName,
            Optional<Boolean> showAsButton,
            Optional<Boolean> assignMembershipOnLogin,
            Optional<Boolean> isEnabled,
            Optional<IdpGoogleAppsOptionsRequest> options,
            Map<String, Object> additionalProperties) {
        this.displayName = displayName;
        this.showAsButton = showAsButton;
        this.assignMembershipOnLogin = assignMembershipOnLogin;
        this.isEnabled = isEnabled;
        this.options = options;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Identity provider name used on the login screen. Requires access_level to be 'full'
     */
    @JsonProperty("display_name")
    @Override
    public Optional<String> getDisplayName() {
        return displayName;
    }

    /**
     * @return Enables showing a button for the connection in the login page (new experience only). If false, it will be usable only by Home Realm Discovery (HRD). Requires access_level to be 'full' or 'limited'
     */
    @JsonProperty("show_as_button")
    @Override
    public Optional<Boolean> getShowAsButton() {
        return showAsButton;
    }

    /**
     * @return If true, the user will be made a member of the organization upon login. Requires access_level to be 'full' or 'limited'.
     */
    @JsonProperty("assign_membership_on_login")
    @Override
    public Optional<Boolean> getAssignMembershipOnLogin() {
        return assignMembershipOnLogin;
    }

    /**
     * @return True if the identity provider is enabled for the organization. Requires access_level to be 'full' or 'limited'
     */
    @JsonProperty("is_enabled")
    @Override
    public Optional<Boolean> getIsEnabled() {
        return isEnabled;
    }

    /**
     * @return Identity provider specific options.  Requires access_level to be 'full'.
     */
    @JsonProperty("options")
    public Optional<IdpGoogleAppsOptionsRequest> getOptions() {
        return options;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof IdpGoogleAppsUpdateRequest && equalTo((IdpGoogleAppsUpdateRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(IdpGoogleAppsUpdateRequest other) {
        return displayName.equals(other.displayName)
                && showAsButton.equals(other.showAsButton)
                && assignMembershipOnLogin.equals(other.assignMembershipOnLogin)
                && isEnabled.equals(other.isEnabled)
                && options.equals(other.options);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                this.displayName, this.showAsButton, this.assignMembershipOnLogin, this.isEnabled, this.options);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> displayName = Optional.empty();

        private Optional<Boolean> showAsButton = Optional.empty();

        private Optional<Boolean> assignMembershipOnLogin = Optional.empty();

        private Optional<Boolean> isEnabled = Optional.empty();

        private Optional<IdpGoogleAppsOptionsRequest> options = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(IdpGoogleAppsUpdateRequest other) {
            displayName(other.getDisplayName());
            showAsButton(other.getShowAsButton());
            assignMembershipOnLogin(other.getAssignMembershipOnLogin());
            isEnabled(other.getIsEnabled());
            options(other.getOptions());
            return this;
        }

        /**
         * <p>Identity provider name used on the login screen. Requires access_level to be 'full'</p>
         */
        @JsonSetter(value = "display_name", nulls = Nulls.SKIP)
        public Builder displayName(Optional<String> displayName) {
            this.displayName = displayName;
            return this;
        }

        public Builder displayName(String displayName) {
            this.displayName = Optional.ofNullable(displayName);
            return this;
        }

        /**
         * <p>Enables showing a button for the connection in the login page (new experience only). If false, it will be usable only by Home Realm Discovery (HRD). Requires access_level to be 'full' or 'limited'</p>
         */
        @JsonSetter(value = "show_as_button", nulls = Nulls.SKIP)
        public Builder showAsButton(Optional<Boolean> showAsButton) {
            this.showAsButton = showAsButton;
            return this;
        }

        public Builder showAsButton(Boolean showAsButton) {
            this.showAsButton = Optional.ofNullable(showAsButton);
            return this;
        }

        /**
         * <p>If true, the user will be made a member of the organization upon login. Requires access_level to be 'full' or 'limited'.</p>
         */
        @JsonSetter(value = "assign_membership_on_login", nulls = Nulls.SKIP)
        public Builder assignMembershipOnLogin(Optional<Boolean> assignMembershipOnLogin) {
            this.assignMembershipOnLogin = assignMembershipOnLogin;
            return this;
        }

        public Builder assignMembershipOnLogin(Boolean assignMembershipOnLogin) {
            this.assignMembershipOnLogin = Optional.ofNullable(assignMembershipOnLogin);
            return this;
        }

        /**
         * <p>True if the identity provider is enabled for the organization. Requires access_level to be 'full' or 'limited'</p>
         */
        @JsonSetter(value = "is_enabled", nulls = Nulls.SKIP)
        public Builder isEnabled(Optional<Boolean> isEnabled) {
            this.isEnabled = isEnabled;
            return this;
        }

        public Builder isEnabled(Boolean isEnabled) {
            this.isEnabled = Optional.ofNullable(isEnabled);
            return this;
        }

        /**
         * <p>Identity provider specific options.  Requires access_level to be 'full'.</p>
         */
        @JsonSetter(value = "options", nulls = Nulls.SKIP)
        public Builder options(Optional<IdpGoogleAppsOptionsRequest> options) {
            this.options = options;
            return this;
        }

        public Builder options(IdpGoogleAppsOptionsRequest options) {
            this.options = Optional.ofNullable(options);
            return this;
        }

        public IdpGoogleAppsUpdateRequest build() {
            return new IdpGoogleAppsUpdateRequest(
                    displayName, showAsButton, assignMembershipOnLogin, isEnabled, options, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
