/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class IdpGoogleAppsResponseStrategy {
    public static final IdpGoogleAppsResponseStrategy GOOGLE_APPS =
            new IdpGoogleAppsResponseStrategy(Value.GOOGLE_APPS, "google-apps");

    private final Value value;

    private final String string;

    IdpGoogleAppsResponseStrategy(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof IdpGoogleAppsResponseStrategy
                        && this.string.equals(((IdpGoogleAppsResponseStrategy) other).string));
    }

    @Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case GOOGLE_APPS:
                return visitor.visitGoogleApps();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static IdpGoogleAppsResponseStrategy valueOf(String value) {
        switch (value) {
            case "google-apps":
                return GOOGLE_APPS;
            default:
                return new IdpGoogleAppsResponseStrategy(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        GOOGLE_APPS,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitGoogleApps();

        T visitUnknown(String unknownType);
    }
}
