/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.auth0.client.myorganization.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = IdpOidcOptionsResponse.Builder.class)
public final class IdpOidcOptionsResponse {
    private final Optional<IdpOidcOptionsTypeEnum> type;

    private final Optional<String> clientId;

    private final Optional<String> discoveryUrl;

    private final Map<String, Object> additionalProperties;

    private IdpOidcOptionsResponse(
            Optional<IdpOidcOptionsTypeEnum> type,
            Optional<String> clientId,
            Optional<String> discoveryUrl,
            Map<String, Object> additionalProperties) {
        this.type = type;
        this.clientId = clientId;
        this.discoveryUrl = discoveryUrl;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("type")
    public Optional<IdpOidcOptionsTypeEnum> getType() {
        return type;
    }

    /**
     * @return The identifier given to you by your provider. Unique identifier for your registered application.
     */
    @JsonProperty("client_id")
    public Optional<String> getClientId() {
        return clientId;
    }

    /**
     * @return The URL where the OIDC Identity Provider publishes its OpenID Provider Configuration Information
     */
    @JsonProperty("discovery_url")
    public Optional<String> getDiscoveryUrl() {
        return discoveryUrl;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof IdpOidcOptionsResponse && equalTo((IdpOidcOptionsResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(IdpOidcOptionsResponse other) {
        return type.equals(other.type) && clientId.equals(other.clientId) && discoveryUrl.equals(other.discoveryUrl);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.type, this.clientId, this.discoveryUrl);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<IdpOidcOptionsTypeEnum> type = Optional.empty();

        private Optional<String> clientId = Optional.empty();

        private Optional<String> discoveryUrl = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(IdpOidcOptionsResponse other) {
            type(other.getType());
            clientId(other.getClientId());
            discoveryUrl(other.getDiscoveryUrl());
            return this;
        }

        @JsonSetter(value = "type", nulls = Nulls.SKIP)
        public Builder type(Optional<IdpOidcOptionsTypeEnum> type) {
            this.type = type;
            return this;
        }

        public Builder type(IdpOidcOptionsTypeEnum type) {
            this.type = Optional.ofNullable(type);
            return this;
        }

        /**
         * <p>The identifier given to you by your provider. Unique identifier for your registered application.</p>
         */
        @JsonSetter(value = "client_id", nulls = Nulls.SKIP)
        public Builder clientId(Optional<String> clientId) {
            this.clientId = clientId;
            return this;
        }

        public Builder clientId(String clientId) {
            this.clientId = Optional.ofNullable(clientId);
            return this;
        }

        /**
         * <p>The URL where the OIDC Identity Provider publishes its OpenID Provider Configuration Information</p>
         */
        @JsonSetter(value = "discovery_url", nulls = Nulls.SKIP)
        public Builder discoveryUrl(Optional<String> discoveryUrl) {
            this.discoveryUrl = discoveryUrl;
            return this;
        }

        public Builder discoveryUrl(String discoveryUrl) {
            this.discoveryUrl = Optional.ofNullable(discoveryUrl);
            return this;
        }

        public IdpOidcOptionsResponse build() {
            return new IdpOidcOptionsResponse(type, clientId, discoveryUrl, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
