/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.auth0.client.myorganization.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = IdpOktaOptionsRequest.Builder.class)
public final class IdpOktaOptionsRequest {
    private final String domain;

    private final String clientId;

    private final String clientSecret;

    private final Optional<String> iconUrl;

    private final Map<String, Object> additionalProperties;

    private IdpOktaOptionsRequest(
            String domain,
            String clientId,
            String clientSecret,
            Optional<String> iconUrl,
            Map<String, Object> additionalProperties) {
        this.domain = domain;
        this.clientId = clientId;
        this.clientSecret = clientSecret;
        this.iconUrl = iconUrl;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Okta's domain name for your organization.
     */
    @JsonProperty("domain")
    public String getDomain() {
        return domain;
    }

    /**
     * @return Unique identifier for your registered Okta application
     */
    @JsonProperty("client_id")
    public String getClientId() {
        return clientId;
    }

    /**
     * @return String used to gain access to your registered Okta application.
     */
    @JsonProperty("client_secret")
    public String getClientSecret() {
        return clientSecret;
    }

    /**
     * @return A URL pointing to an image file that represents your client application.
     */
    @JsonProperty("icon_url")
    public Optional<String> getIconUrl() {
        return iconUrl;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof IdpOktaOptionsRequest && equalTo((IdpOktaOptionsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(IdpOktaOptionsRequest other) {
        return domain.equals(other.domain)
                && clientId.equals(other.clientId)
                && clientSecret.equals(other.clientSecret)
                && iconUrl.equals(other.iconUrl);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.domain, this.clientId, this.clientSecret, this.iconUrl);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static DomainStage builder() {
        return new Builder();
    }

    public interface DomainStage {
        /**
         * <p>Okta's domain name for your organization.</p>
         */
        ClientIdStage domain(@NotNull String domain);

        Builder from(IdpOktaOptionsRequest other);
    }

    public interface ClientIdStage {
        /**
         * <p>Unique identifier for your registered Okta application</p>
         */
        ClientSecretStage clientId(@NotNull String clientId);
    }

    public interface ClientSecretStage {
        /**
         * <p>String used to gain access to your registered Okta application.</p>
         */
        _FinalStage clientSecret(@NotNull String clientSecret);
    }

    public interface _FinalStage {
        IdpOktaOptionsRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>A URL pointing to an image file that represents your client application.</p>
         */
        _FinalStage iconUrl(Optional<String> iconUrl);

        _FinalStage iconUrl(String iconUrl);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements DomainStage, ClientIdStage, ClientSecretStage, _FinalStage {
        private String domain;

        private String clientId;

        private String clientSecret;

        private Optional<String> iconUrl = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(IdpOktaOptionsRequest other) {
            domain(other.getDomain());
            clientId(other.getClientId());
            clientSecret(other.getClientSecret());
            iconUrl(other.getIconUrl());
            return this;
        }

        /**
         * <p>Okta's domain name for your organization.</p>
         * <p>Okta's domain name for your organization.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("domain")
        public ClientIdStage domain(@NotNull String domain) {
            this.domain = Objects.requireNonNull(domain, "domain must not be null");
            return this;
        }

        /**
         * <p>Unique identifier for your registered Okta application</p>
         * <p>Unique identifier for your registered Okta application</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("client_id")
        public ClientSecretStage clientId(@NotNull String clientId) {
            this.clientId = Objects.requireNonNull(clientId, "clientId must not be null");
            return this;
        }

        /**
         * <p>String used to gain access to your registered Okta application.</p>
         * <p>String used to gain access to your registered Okta application.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("client_secret")
        public _FinalStage clientSecret(@NotNull String clientSecret) {
            this.clientSecret = Objects.requireNonNull(clientSecret, "clientSecret must not be null");
            return this;
        }

        /**
         * <p>A URL pointing to an image file that represents your client application.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage iconUrl(String iconUrl) {
            this.iconUrl = Optional.ofNullable(iconUrl);
            return this;
        }

        /**
         * <p>A URL pointing to an image file that represents your client application.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "icon_url", nulls = Nulls.SKIP)
        public _FinalStage iconUrl(Optional<String> iconUrl) {
            this.iconUrl = iconUrl;
            return this;
        }

        @java.lang.Override
        public IdpOktaOptionsRequest build() {
            return new IdpOktaOptionsRequest(domain, clientId, clientSecret, iconUrl, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
