/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class IdpOidcRequestStrategy {
    public static final IdpOidcRequestStrategy OIDC = new IdpOidcRequestStrategy(Value.OIDC, "oidc");

    private final Value value;

    private final String string;

    IdpOidcRequestStrategy(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof IdpOidcRequestStrategy
                        && this.string.equals(((IdpOidcRequestStrategy) other).string));
    }

    @Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case OIDC:
                return visitor.visitOidc();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static IdpOidcRequestStrategy valueOf(String value) {
        switch (value) {
            case "oidc":
                return OIDC;
            default:
                return new IdpOidcRequestStrategy(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        OIDC,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitOidc();

        T visitUnknown(String unknownType);
    }
}
