/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.auth0.client.myorganization.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = IdpOptionsIdpInitiated.Builder.class)
public final class IdpOptionsIdpInitiated {
    private final Optional<Boolean> enabled;

    private final Optional<String> clientId;

    private final Optional<String> clientProtocol;

    private final Optional<String> clientAuthorizequery;

    private final Map<String, Object> additionalProperties;

    private IdpOptionsIdpInitiated(
            Optional<Boolean> enabled,
            Optional<String> clientId,
            Optional<String> clientProtocol,
            Optional<String> clientAuthorizequery,
            Map<String, Object> additionalProperties) {
        this.enabled = enabled;
        this.clientId = clientId;
        this.clientProtocol = clientProtocol;
        this.clientAuthorizequery = clientAuthorizequery;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return A flag indicating whether IdP-initiated SSO is enabled for this connection
     */
    @JsonProperty("enabled")
    public Optional<Boolean> getEnabled() {
        return enabled;
    }

    /**
     * @return The client ID of your default application for which the IdP-initiated flow is being configured
     */
    @JsonProperty("client_id")
    public Optional<String> getClientId() {
        return clientId;
    }

    /**
     * @return This is the protocol used to connect your selected default application
     */
    @JsonProperty("client_protocol")
    public Optional<String> getClientProtocol() {
        return clientProtocol;
    }

    /**
     * @return This field represents a template for constructing the authorization query string when initiating an IdP-initiated flow to a specific client
     */
    @JsonProperty("client_authorizequery")
    public Optional<String> getClientAuthorizequery() {
        return clientAuthorizequery;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof IdpOptionsIdpInitiated && equalTo((IdpOptionsIdpInitiated) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(IdpOptionsIdpInitiated other) {
        return enabled.equals(other.enabled)
                && clientId.equals(other.clientId)
                && clientProtocol.equals(other.clientProtocol)
                && clientAuthorizequery.equals(other.clientAuthorizequery);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.enabled, this.clientId, this.clientProtocol, this.clientAuthorizequery);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Boolean> enabled = Optional.empty();

        private Optional<String> clientId = Optional.empty();

        private Optional<String> clientProtocol = Optional.empty();

        private Optional<String> clientAuthorizequery = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(IdpOptionsIdpInitiated other) {
            enabled(other.getEnabled());
            clientId(other.getClientId());
            clientProtocol(other.getClientProtocol());
            clientAuthorizequery(other.getClientAuthorizequery());
            return this;
        }

        /**
         * <p>A flag indicating whether IdP-initiated SSO is enabled for this connection</p>
         */
        @JsonSetter(value = "enabled", nulls = Nulls.SKIP)
        public Builder enabled(Optional<Boolean> enabled) {
            this.enabled = enabled;
            return this;
        }

        public Builder enabled(Boolean enabled) {
            this.enabled = Optional.ofNullable(enabled);
            return this;
        }

        /**
         * <p>The client ID of your default application for which the IdP-initiated flow is being configured</p>
         */
        @JsonSetter(value = "client_id", nulls = Nulls.SKIP)
        public Builder clientId(Optional<String> clientId) {
            this.clientId = clientId;
            return this;
        }

        public Builder clientId(String clientId) {
            this.clientId = Optional.ofNullable(clientId);
            return this;
        }

        /**
         * <p>This is the protocol used to connect your selected default application</p>
         */
        @JsonSetter(value = "client_protocol", nulls = Nulls.SKIP)
        public Builder clientProtocol(Optional<String> clientProtocol) {
            this.clientProtocol = clientProtocol;
            return this;
        }

        public Builder clientProtocol(String clientProtocol) {
            this.clientProtocol = Optional.ofNullable(clientProtocol);
            return this;
        }

        /**
         * <p>This field represents a template for constructing the authorization query string when initiating an IdP-initiated flow to a specific client</p>
         */
        @JsonSetter(value = "client_authorizequery", nulls = Nulls.SKIP)
        public Builder clientAuthorizequery(Optional<String> clientAuthorizequery) {
            this.clientAuthorizequery = clientAuthorizequery;
            return this;
        }

        public Builder clientAuthorizequery(String clientAuthorizequery) {
            this.clientAuthorizequery = Optional.ofNullable(clientAuthorizequery);
            return this;
        }

        public IdpOptionsIdpInitiated build() {
            return new IdpOptionsIdpInitiated(
                    enabled, clientId, clientProtocol, clientAuthorizequery, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
