/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.auth0.client.myorganization.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = IdpOktaUpdateRequest.Builder.class)
public final class IdpOktaUpdateRequest implements IIdpUpdateBase {
    private final Optional<String> displayName;

    private final Optional<Boolean> showAsButton;

    private final Optional<Boolean> assignMembershipOnLogin;

    private final Optional<Boolean> isEnabled;

    private final Optional<Boolean> useForThirdPartyClientAccess;

    private final Optional<CrossAppAccessResourceApp> crossAppAccessResourceApp;

    private final Optional<IdpOktaOptionsRequest> options;

    private final Map<String, Object> additionalProperties;

    private IdpOktaUpdateRequest(
            Optional<String> displayName,
            Optional<Boolean> showAsButton,
            Optional<Boolean> assignMembershipOnLogin,
            Optional<Boolean> isEnabled,
            Optional<Boolean> useForThirdPartyClientAccess,
            Optional<CrossAppAccessResourceApp> crossAppAccessResourceApp,
            Optional<IdpOktaOptionsRequest> options,
            Map<String, Object> additionalProperties) {
        this.displayName = displayName;
        this.showAsButton = showAsButton;
        this.assignMembershipOnLogin = assignMembershipOnLogin;
        this.isEnabled = isEnabled;
        this.useForThirdPartyClientAccess = useForThirdPartyClientAccess;
        this.crossAppAccessResourceApp = crossAppAccessResourceApp;
        this.options = options;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Identity provider name used on the login screen. Requires access_level to be 'full'
     */
    @JsonProperty("display_name")
    @java.lang.Override
    public Optional<String> getDisplayName() {
        return displayName;
    }

    /**
     * @return Enables showing a button for the connection in the login page (new experience only). If false, it will be usable only by Home Realm Discovery (HRD). Requires access_level to be 'full' or 'limited'
     */
    @JsonProperty("show_as_button")
    @java.lang.Override
    public Optional<Boolean> getShowAsButton() {
        return showAsButton;
    }

    /**
     * @return If true, the user will be made a member of the organization upon login. Requires access_level to be 'full' or 'limited'.
     */
    @JsonProperty("assign_membership_on_login")
    @java.lang.Override
    public Optional<Boolean> getAssignMembershipOnLogin() {
        return assignMembershipOnLogin;
    }

    /**
     * @return True if the identity provider is enabled for the organization. Requires access_level to be 'full' or 'limited'
     */
    @JsonProperty("is_enabled")
    @java.lang.Override
    public Optional<Boolean> getIsEnabled() {
        return isEnabled;
    }

    /**
     * @return True if third-party applications can use it. If false, only first-party applications with the connection enabled can use it. Requires access_level to be 'full'. Defaults to false.
     */
    @JsonProperty("use_for_third_party_client_access")
    @java.lang.Override
    public Optional<Boolean> getUseForThirdPartyClientAccess() {
        return useForThirdPartyClientAccess;
    }

    /**
     * @return Cross-app access resource application configuration. Only present when the cross-app access resource application feature is enabled for your organization.
     */
    @JsonProperty("cross_app_access_resource_app")
    @java.lang.Override
    public Optional<CrossAppAccessResourceApp> getCrossAppAccessResourceApp() {
        return crossAppAccessResourceApp;
    }

    /**
     * @return Identity provider specific options.  Requires access_level to be 'full'.
     */
    @JsonProperty("options")
    public Optional<IdpOktaOptionsRequest> getOptions() {
        return options;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof IdpOktaUpdateRequest && equalTo((IdpOktaUpdateRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(IdpOktaUpdateRequest other) {
        return displayName.equals(other.displayName)
                && showAsButton.equals(other.showAsButton)
                && assignMembershipOnLogin.equals(other.assignMembershipOnLogin)
                && isEnabled.equals(other.isEnabled)
                && useForThirdPartyClientAccess.equals(other.useForThirdPartyClientAccess)
                && crossAppAccessResourceApp.equals(other.crossAppAccessResourceApp)
                && options.equals(other.options);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.displayName,
                this.showAsButton,
                this.assignMembershipOnLogin,
                this.isEnabled,
                this.useForThirdPartyClientAccess,
                this.crossAppAccessResourceApp,
                this.options);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> displayName = Optional.empty();

        private Optional<Boolean> showAsButton = Optional.empty();

        private Optional<Boolean> assignMembershipOnLogin = Optional.empty();

        private Optional<Boolean> isEnabled = Optional.empty();

        private Optional<Boolean> useForThirdPartyClientAccess = Optional.empty();

        private Optional<CrossAppAccessResourceApp> crossAppAccessResourceApp = Optional.empty();

        private Optional<IdpOktaOptionsRequest> options = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(IdpOktaUpdateRequest other) {
            displayName(other.getDisplayName());
            showAsButton(other.getShowAsButton());
            assignMembershipOnLogin(other.getAssignMembershipOnLogin());
            isEnabled(other.getIsEnabled());
            useForThirdPartyClientAccess(other.getUseForThirdPartyClientAccess());
            crossAppAccessResourceApp(other.getCrossAppAccessResourceApp());
            options(other.getOptions());
            return this;
        }

        /**
         * <p>Identity provider name used on the login screen. Requires access_level to be 'full'</p>
         */
        @JsonSetter(value = "display_name", nulls = Nulls.SKIP)
        public Builder displayName(Optional<String> displayName) {
            this.displayName = displayName;
            return this;
        }

        public Builder displayName(String displayName) {
            this.displayName = Optional.ofNullable(displayName);
            return this;
        }

        /**
         * <p>Enables showing a button for the connection in the login page (new experience only). If false, it will be usable only by Home Realm Discovery (HRD). Requires access_level to be 'full' or 'limited'</p>
         */
        @JsonSetter(value = "show_as_button", nulls = Nulls.SKIP)
        public Builder showAsButton(Optional<Boolean> showAsButton) {
            this.showAsButton = showAsButton;
            return this;
        }

        public Builder showAsButton(Boolean showAsButton) {
            this.showAsButton = Optional.ofNullable(showAsButton);
            return this;
        }

        /**
         * <p>If true, the user will be made a member of the organization upon login. Requires access_level to be 'full' or 'limited'.</p>
         */
        @JsonSetter(value = "assign_membership_on_login", nulls = Nulls.SKIP)
        public Builder assignMembershipOnLogin(Optional<Boolean> assignMembershipOnLogin) {
            this.assignMembershipOnLogin = assignMembershipOnLogin;
            return this;
        }

        public Builder assignMembershipOnLogin(Boolean assignMembershipOnLogin) {
            this.assignMembershipOnLogin = Optional.ofNullable(assignMembershipOnLogin);
            return this;
        }

        /**
         * <p>True if the identity provider is enabled for the organization. Requires access_level to be 'full' or 'limited'</p>
         */
        @JsonSetter(value = "is_enabled", nulls = Nulls.SKIP)
        public Builder isEnabled(Optional<Boolean> isEnabled) {
            this.isEnabled = isEnabled;
            return this;
        }

        public Builder isEnabled(Boolean isEnabled) {
            this.isEnabled = Optional.ofNullable(isEnabled);
            return this;
        }

        /**
         * <p>True if third-party applications can use it. If false, only first-party applications with the connection enabled can use it. Requires access_level to be 'full'. Defaults to false.</p>
         */
        @JsonSetter(value = "use_for_third_party_client_access", nulls = Nulls.SKIP)
        public Builder useForThirdPartyClientAccess(Optional<Boolean> useForThirdPartyClientAccess) {
            this.useForThirdPartyClientAccess = useForThirdPartyClientAccess;
            return this;
        }

        public Builder useForThirdPartyClientAccess(Boolean useForThirdPartyClientAccess) {
            this.useForThirdPartyClientAccess = Optional.ofNullable(useForThirdPartyClientAccess);
            return this;
        }

        /**
         * <p>Cross-app access resource application configuration. Only present when the cross-app access resource application feature is enabled for your organization.</p>
         */
        @JsonSetter(value = "cross_app_access_resource_app", nulls = Nulls.SKIP)
        public Builder crossAppAccessResourceApp(Optional<CrossAppAccessResourceApp> crossAppAccessResourceApp) {
            this.crossAppAccessResourceApp = crossAppAccessResourceApp;
            return this;
        }

        public Builder crossAppAccessResourceApp(CrossAppAccessResourceApp crossAppAccessResourceApp) {
            this.crossAppAccessResourceApp = Optional.ofNullable(crossAppAccessResourceApp);
            return this;
        }

        /**
         * <p>Identity provider specific options.  Requires access_level to be 'full'.</p>
         */
        @JsonSetter(value = "options", nulls = Nulls.SKIP)
        public Builder options(Optional<IdpOktaOptionsRequest> options) {
            this.options = options;
            return this;
        }

        public Builder options(IdpOktaOptionsRequest options) {
            this.options = Optional.ofNullable(options);
            return this;
        }

        public IdpOktaUpdateRequest build() {
            return new IdpOktaUpdateRequest(
                    displayName,
                    showAsButton,
                    assignMembershipOnLogin,
                    isEnabled,
                    useForThirdPartyClientAccess,
                    crossAppAccessResourceApp,
                    options,
                    additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
