/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.auth0.client.myorganization.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = IdpProvisioningUserAttributeMapItem.Builder.class)
public final class IdpProvisioningUserAttributeMapItem implements IBaseUserAttributeMapItem {
    private final Optional<String> userAttribute;

    private final Optional<String> description;

    private final Optional<String> label;

    private final boolean isRequired;

    private final boolean isExtra;

    private final boolean isMissing;

    private final String provisioningField;

    private final Map<String, Object> additionalProperties;

    private IdpProvisioningUserAttributeMapItem(
            Optional<String> userAttribute,
            Optional<String> description,
            Optional<String> label,
            boolean isRequired,
            boolean isExtra,
            boolean isMissing,
            String provisioningField,
            Map<String, Object> additionalProperties) {
        this.userAttribute = userAttribute;
        this.description = description;
        this.label = label;
        this.isRequired = isRequired;
        this.isExtra = isExtra;
        this.isMissing = isMissing;
        this.provisioningField = provisioningField;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The name of the user attribute.
     */
    @JsonProperty("user_attribute")
    @Override
    public Optional<String> getUserAttribute() {
        return userAttribute;
    }

    /**
     * @return The description of the user attribute.
     */
    @JsonProperty("description")
    @Override
    public Optional<String> getDescription() {
        return description;
    }

    /**
     * @return The label of the user attribute.
     */
    @JsonProperty("label")
    @Override
    public Optional<String> getLabel() {
        return label;
    }

    /**
     * @return Indicates if the attribute is required.
     */
    @JsonProperty("is_required")
    @Override
    public boolean getIsRequired() {
        return isRequired;
    }

    /**
     * @return Indicates whether this attribute is not part of the admin defined schema but is provided by the source. The property will be removed when a refresh operation is performed.
     */
    @JsonProperty("is_extra")
    @Override
    public boolean getIsExtra() {
        return isExtra;
    }

    /**
     * @return Indicates whether this attribute is expected but not provided by the admin defined schema. The property will be added when a refresh operation is performed.
     */
    @JsonProperty("is_missing")
    @Override
    public boolean getIsMissing() {
        return isMissing;
    }

    /**
     * @return The name of the provisioning field.
     */
    @JsonProperty("provisioning_field")
    public String getProvisioningField() {
        return provisioningField;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof IdpProvisioningUserAttributeMapItem
                && equalTo((IdpProvisioningUserAttributeMapItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(IdpProvisioningUserAttributeMapItem other) {
        return userAttribute.equals(other.userAttribute)
                && description.equals(other.description)
                && label.equals(other.label)
                && isRequired == other.isRequired
                && isExtra == other.isExtra
                && isMissing == other.isMissing
                && provisioningField.equals(other.provisioningField);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                this.userAttribute,
                this.description,
                this.label,
                this.isRequired,
                this.isExtra,
                this.isMissing,
                this.provisioningField);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IsRequiredStage builder() {
        return new Builder();
    }

    public interface IsRequiredStage {
        /**
         * <p>Indicates if the attribute is required.</p>
         */
        IsExtraStage isRequired(boolean isRequired);

        Builder from(IdpProvisioningUserAttributeMapItem other);
    }

    public interface IsExtraStage {
        /**
         * <p>Indicates whether this attribute is not part of the admin defined schema but is provided by the source. The property will be removed when a refresh operation is performed.</p>
         */
        IsMissingStage isExtra(boolean isExtra);
    }

    public interface IsMissingStage {
        /**
         * <p>Indicates whether this attribute is expected but not provided by the admin defined schema. The property will be added when a refresh operation is performed.</p>
         */
        ProvisioningFieldStage isMissing(boolean isMissing);
    }

    public interface ProvisioningFieldStage {
        /**
         * <p>The name of the provisioning field.</p>
         */
        _FinalStage provisioningField(@NotNull String provisioningField);
    }

    public interface _FinalStage {
        IdpProvisioningUserAttributeMapItem build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>The name of the user attribute.</p>
         */
        _FinalStage userAttribute(Optional<String> userAttribute);

        _FinalStage userAttribute(String userAttribute);

        /**
         * <p>The description of the user attribute.</p>
         */
        _FinalStage description(Optional<String> description);

        _FinalStage description(String description);

        /**
         * <p>The label of the user attribute.</p>
         */
        _FinalStage label(Optional<String> label);

        _FinalStage label(String label);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements IsRequiredStage, IsExtraStage, IsMissingStage, ProvisioningFieldStage, _FinalStage {
        private boolean isRequired;

        private boolean isExtra;

        private boolean isMissing;

        private String provisioningField;

        private Optional<String> label = Optional.empty();

        private Optional<String> description = Optional.empty();

        private Optional<String> userAttribute = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @Override
        public Builder from(IdpProvisioningUserAttributeMapItem other) {
            userAttribute(other.getUserAttribute());
            description(other.getDescription());
            label(other.getLabel());
            isRequired(other.getIsRequired());
            isExtra(other.getIsExtra());
            isMissing(other.getIsMissing());
            provisioningField(other.getProvisioningField());
            return this;
        }

        /**
         * <p>Indicates if the attribute is required.</p>
         * <p>Indicates if the attribute is required.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        @JsonSetter("is_required")
        public IsExtraStage isRequired(boolean isRequired) {
            this.isRequired = isRequired;
            return this;
        }

        /**
         * <p>Indicates whether this attribute is not part of the admin defined schema but is provided by the source. The property will be removed when a refresh operation is performed.</p>
         * <p>Indicates whether this attribute is not part of the admin defined schema but is provided by the source. The property will be removed when a refresh operation is performed.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        @JsonSetter("is_extra")
        public IsMissingStage isExtra(boolean isExtra) {
            this.isExtra = isExtra;
            return this;
        }

        /**
         * <p>Indicates whether this attribute is expected but not provided by the admin defined schema. The property will be added when a refresh operation is performed.</p>
         * <p>Indicates whether this attribute is expected but not provided by the admin defined schema. The property will be added when a refresh operation is performed.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        @JsonSetter("is_missing")
        public ProvisioningFieldStage isMissing(boolean isMissing) {
            this.isMissing = isMissing;
            return this;
        }

        /**
         * <p>The name of the provisioning field.</p>
         * <p>The name of the provisioning field.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        @JsonSetter("provisioning_field")
        public _FinalStage provisioningField(@NotNull String provisioningField) {
            this.provisioningField = Objects.requireNonNull(provisioningField, "provisioningField must not be null");
            return this;
        }

        /**
         * <p>The label of the user attribute.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        public _FinalStage label(String label) {
            this.label = Optional.ofNullable(label);
            return this;
        }

        /**
         * <p>The label of the user attribute.</p>
         */
        @Override
        @JsonSetter(value = "label", nulls = Nulls.SKIP)
        public _FinalStage label(Optional<String> label) {
            this.label = label;
            return this;
        }

        /**
         * <p>The description of the user attribute.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        public _FinalStage description(String description) {
            this.description = Optional.ofNullable(description);
            return this;
        }

        /**
         * <p>The description of the user attribute.</p>
         */
        @Override
        @JsonSetter(value = "description", nulls = Nulls.SKIP)
        public _FinalStage description(Optional<String> description) {
            this.description = description;
            return this;
        }

        /**
         * <p>The name of the user attribute.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        public _FinalStage userAttribute(String userAttribute) {
            this.userAttribute = Optional.ofNullable(userAttribute);
            return this;
        }

        /**
         * <p>The name of the user attribute.</p>
         */
        @Override
        @JsonSetter(value = "user_attribute", nulls = Nulls.SKIP)
        public _FinalStage userAttribute(Optional<String> userAttribute) {
            this.userAttribute = userAttribute;
            return this;
        }

        @Override
        public IdpProvisioningUserAttributeMapItem build() {
            return new IdpProvisioningUserAttributeMapItem(
                    userAttribute,
                    description,
                    label,
                    isRequired,
                    isExtra,
                    isMissing,
                    provisioningField,
                    additionalProperties);
        }

        @Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
