/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.auth0.client.myorganization.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = IdpPingFederateOptionsRequest.Builder.class)
public final class IdpPingFederateOptionsRequest {
    private final IdpSignAlgTypeEnum signatureAlgorithm;

    private final IdpSignAlgDigestTypeEnum digestAlgorithm;

    private final boolean signSamlRequest;

    private final String pingFederateBaseUrl;

    private final String signingCert;

    private final Optional<IdpOptionsIdpInitiated> idpInitiated;

    private final Optional<String> iconUrl;

    private final Map<String, Object> additionalProperties;

    private IdpPingFederateOptionsRequest(
            IdpSignAlgTypeEnum signatureAlgorithm,
            IdpSignAlgDigestTypeEnum digestAlgorithm,
            boolean signSamlRequest,
            String pingFederateBaseUrl,
            String signingCert,
            Optional<IdpOptionsIdpInitiated> idpInitiated,
            Optional<String> iconUrl,
            Map<String, Object> additionalProperties) {
        this.signatureAlgorithm = signatureAlgorithm;
        this.digestAlgorithm = digestAlgorithm;
        this.signSamlRequest = signSamlRequest;
        this.pingFederateBaseUrl = pingFederateBaseUrl;
        this.signingCert = signingCert;
        this.idpInitiated = idpInitiated;
        this.iconUrl = iconUrl;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("signatureAlgorithm")
    public IdpSignAlgTypeEnum getSignatureAlgorithm() {
        return signatureAlgorithm;
    }

    @JsonProperty("digestAlgorithm")
    public IdpSignAlgDigestTypeEnum getDigestAlgorithm() {
        return digestAlgorithm;
    }

    /**
     * @return Indicates whether PingFederate should digitally sign outgoing SAML authentication requests to relying parties
     */
    @JsonProperty("signSAMLRequest")
    public boolean getSignSamlRequest() {
        return signSamlRequest;
    }

    /**
     * @return URL provided by PingFederate which returns information used for creating the connection
     */
    @JsonProperty("pingFederateBaseUrl")
    public String getPingFederateBaseUrl() {
        return pingFederateBaseUrl;
    }

    /**
     * @return PingFederate Server public key (encoded in PEM or CER) you retrieved from the IdP
     */
    @JsonProperty("signingCert")
    public String getSigningCert() {
        return signingCert;
    }

    @JsonProperty("idpInitiated")
    public Optional<IdpOptionsIdpInitiated> getIdpInitiated() {
        return idpInitiated;
    }

    /**
     * @return A URL pointing to an image file that represents your client application.
     */
    @JsonProperty("icon_url")
    public Optional<String> getIconUrl() {
        return iconUrl;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof IdpPingFederateOptionsRequest && equalTo((IdpPingFederateOptionsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(IdpPingFederateOptionsRequest other) {
        return signatureAlgorithm.equals(other.signatureAlgorithm)
                && digestAlgorithm.equals(other.digestAlgorithm)
                && signSamlRequest == other.signSamlRequest
                && pingFederateBaseUrl.equals(other.pingFederateBaseUrl)
                && signingCert.equals(other.signingCert)
                && idpInitiated.equals(other.idpInitiated)
                && iconUrl.equals(other.iconUrl);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.signatureAlgorithm,
                this.digestAlgorithm,
                this.signSamlRequest,
                this.pingFederateBaseUrl,
                this.signingCert,
                this.idpInitiated,
                this.iconUrl);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static SignatureAlgorithmStage builder() {
        return new Builder();
    }

    public interface SignatureAlgorithmStage {
        DigestAlgorithmStage signatureAlgorithm(@NotNull IdpSignAlgTypeEnum signatureAlgorithm);

        Builder from(IdpPingFederateOptionsRequest other);
    }

    public interface DigestAlgorithmStage {
        SignSamlRequestStage digestAlgorithm(@NotNull IdpSignAlgDigestTypeEnum digestAlgorithm);
    }

    public interface SignSamlRequestStage {
        /**
         * <p>Indicates whether PingFederate should digitally sign outgoing SAML authentication requests to relying parties</p>
         */
        PingFederateBaseUrlStage signSamlRequest(boolean signSamlRequest);
    }

    public interface PingFederateBaseUrlStage {
        /**
         * <p>URL provided by PingFederate which returns information used for creating the connection</p>
         */
        SigningCertStage pingFederateBaseUrl(@NotNull String pingFederateBaseUrl);
    }

    public interface SigningCertStage {
        /**
         * <p>PingFederate Server public key (encoded in PEM or CER) you retrieved from the IdP</p>
         */
        _FinalStage signingCert(@NotNull String signingCert);
    }

    public interface _FinalStage {
        IdpPingFederateOptionsRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage idpInitiated(Optional<IdpOptionsIdpInitiated> idpInitiated);

        _FinalStage idpInitiated(IdpOptionsIdpInitiated idpInitiated);

        /**
         * <p>A URL pointing to an image file that represents your client application.</p>
         */
        _FinalStage iconUrl(Optional<String> iconUrl);

        _FinalStage iconUrl(String iconUrl);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements SignatureAlgorithmStage,
                    DigestAlgorithmStage,
                    SignSamlRequestStage,
                    PingFederateBaseUrlStage,
                    SigningCertStage,
                    _FinalStage {
        private IdpSignAlgTypeEnum signatureAlgorithm;

        private IdpSignAlgDigestTypeEnum digestAlgorithm;

        private boolean signSamlRequest;

        private String pingFederateBaseUrl;

        private String signingCert;

        private Optional<String> iconUrl = Optional.empty();

        private Optional<IdpOptionsIdpInitiated> idpInitiated = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(IdpPingFederateOptionsRequest other) {
            signatureAlgorithm(other.getSignatureAlgorithm());
            digestAlgorithm(other.getDigestAlgorithm());
            signSamlRequest(other.getSignSamlRequest());
            pingFederateBaseUrl(other.getPingFederateBaseUrl());
            signingCert(other.getSigningCert());
            idpInitiated(other.getIdpInitiated());
            iconUrl(other.getIconUrl());
            return this;
        }

        @java.lang.Override
        @JsonSetter("signatureAlgorithm")
        public DigestAlgorithmStage signatureAlgorithm(@NotNull IdpSignAlgTypeEnum signatureAlgorithm) {
            this.signatureAlgorithm = Objects.requireNonNull(signatureAlgorithm, "signatureAlgorithm must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("digestAlgorithm")
        public SignSamlRequestStage digestAlgorithm(@NotNull IdpSignAlgDigestTypeEnum digestAlgorithm) {
            this.digestAlgorithm = Objects.requireNonNull(digestAlgorithm, "digestAlgorithm must not be null");
            return this;
        }

        /**
         * <p>Indicates whether PingFederate should digitally sign outgoing SAML authentication requests to relying parties</p>
         * <p>Indicates whether PingFederate should digitally sign outgoing SAML authentication requests to relying parties</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("signSAMLRequest")
        public PingFederateBaseUrlStage signSamlRequest(boolean signSamlRequest) {
            this.signSamlRequest = signSamlRequest;
            return this;
        }

        /**
         * <p>URL provided by PingFederate which returns information used for creating the connection</p>
         * <p>URL provided by PingFederate which returns information used for creating the connection</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("pingFederateBaseUrl")
        public SigningCertStage pingFederateBaseUrl(@NotNull String pingFederateBaseUrl) {
            this.pingFederateBaseUrl =
                    Objects.requireNonNull(pingFederateBaseUrl, "pingFederateBaseUrl must not be null");
            return this;
        }

        /**
         * <p>PingFederate Server public key (encoded in PEM or CER) you retrieved from the IdP</p>
         * <p>PingFederate Server public key (encoded in PEM or CER) you retrieved from the IdP</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("signingCert")
        public _FinalStage signingCert(@NotNull String signingCert) {
            this.signingCert = Objects.requireNonNull(signingCert, "signingCert must not be null");
            return this;
        }

        /**
         * <p>A URL pointing to an image file that represents your client application.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage iconUrl(String iconUrl) {
            this.iconUrl = Optional.ofNullable(iconUrl);
            return this;
        }

        /**
         * <p>A URL pointing to an image file that represents your client application.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "icon_url", nulls = Nulls.SKIP)
        public _FinalStage iconUrl(Optional<String> iconUrl) {
            this.iconUrl = iconUrl;
            return this;
        }

        @java.lang.Override
        public _FinalStage idpInitiated(IdpOptionsIdpInitiated idpInitiated) {
            this.idpInitiated = Optional.ofNullable(idpInitiated);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "idpInitiated", nulls = Nulls.SKIP)
        public _FinalStage idpInitiated(Optional<IdpOptionsIdpInitiated> idpInitiated) {
            this.idpInitiated = idpInitiated;
            return this;
        }

        @java.lang.Override
        public IdpPingFederateOptionsRequest build() {
            return new IdpPingFederateOptionsRequest(
                    signatureAlgorithm,
                    digestAlgorithm,
                    signSamlRequest,
                    pingFederateBaseUrl,
                    signingCert,
                    idpInitiated,
                    iconUrl,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
