/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class IdpProvisioningMethodEnum {
    public static final IdpProvisioningMethodEnum SCIM = new IdpProvisioningMethodEnum(Value.SCIM, "scim");

    public static final IdpProvisioningMethodEnum NONE = new IdpProvisioningMethodEnum(Value.NONE, "none");

    private final Value value;

    private final String string;

    IdpProvisioningMethodEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof IdpProvisioningMethodEnum
                        && this.string.equals(((IdpProvisioningMethodEnum) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case SCIM:
                return visitor.visitScim();
            case NONE:
                return visitor.visitNone();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static IdpProvisioningMethodEnum valueOf(String value) {
        switch (value) {
            case "scim":
                return SCIM;
            case "none":
                return NONE;
            default:
                return new IdpProvisioningMethodEnum(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        NONE,

        SCIM,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitNone();

        T visitScim();

        T visitUnknown(String unknownType);
    }
}
