/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.auth0.client.myorganization.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = IdpSamlpOptionsRequestMetadataUrl.Builder.class)
public final class IdpSamlpOptionsRequestMetadataUrl {
    private final String metadataUrl;

    private final boolean signSamlRequest;

    private final Optional<IdpSignAlgTypeEnum> signatureAlgorithm;

    private final Optional<IdpSignAlgDigestTypeEnum> digestAlgorithm;

    private final Optional<IdpProtocolBindingTypeEnum> protocolBinding;

    private final Optional<String> bindingMethod;

    private final Optional<String> signingCert;

    private final Optional<IdpOptionsIdpInitiated> idpInitiated;

    private final Optional<String> iconUrl;

    private final Optional<String> discoveryUrl;

    private final Map<String, Object> additionalProperties;

    private IdpSamlpOptionsRequestMetadataUrl(
            String metadataUrl,
            boolean signSamlRequest,
            Optional<IdpSignAlgTypeEnum> signatureAlgorithm,
            Optional<IdpSignAlgDigestTypeEnum> digestAlgorithm,
            Optional<IdpProtocolBindingTypeEnum> protocolBinding,
            Optional<String> bindingMethod,
            Optional<String> signingCert,
            Optional<IdpOptionsIdpInitiated> idpInitiated,
            Optional<String> iconUrl,
            Optional<String> discoveryUrl,
            Map<String, Object> additionalProperties) {
        this.metadataUrl = metadataUrl;
        this.signSamlRequest = signSamlRequest;
        this.signatureAlgorithm = signatureAlgorithm;
        this.digestAlgorithm = digestAlgorithm;
        this.protocolBinding = protocolBinding;
        this.bindingMethod = bindingMethod;
        this.signingCert = signingCert;
        this.idpInitiated = idpInitiated;
        this.iconUrl = iconUrl;
        this.discoveryUrl = discoveryUrl;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return URL provided by SAML provider which returns information used for creating the connection
     */
    @JsonProperty("metadataUrl")
    public String getMetadataUrl() {
        return metadataUrl;
    }

    /**
     * @return When enabled, the SAML authentication request will be signed.
     */
    @JsonProperty("signSAMLRequest")
    public boolean getSignSamlRequest() {
        return signSamlRequest;
    }

    @JsonProperty("signatureAlgorithm")
    public Optional<IdpSignAlgTypeEnum> getSignatureAlgorithm() {
        return signatureAlgorithm;
    }

    @JsonProperty("digestAlgorithm")
    public Optional<IdpSignAlgDigestTypeEnum> getDigestAlgorithm() {
        return digestAlgorithm;
    }

    @JsonProperty("protocolBinding")
    public Optional<IdpProtocolBindingTypeEnum> getProtocolBinding() {
        return protocolBinding;
    }

    /**
     * @return Defines the specific HTTP binding used for sending SAML messages.
     */
    @JsonProperty("bindingMethod")
    public Optional<String> getBindingMethod() {
        return bindingMethod;
    }

    /**
     * @return Signing certificate (encoded in PEM or CER) you retrieved from the IdP. Optional for this variant: when omitted, the certificate is read from the metadata document.
     */
    @JsonProperty("signingCert")
    public Optional<String> getSigningCert() {
        return signingCert;
    }

    @JsonProperty("idpInitiated")
    public Optional<IdpOptionsIdpInitiated> getIdpInitiated() {
        return idpInitiated;
    }

    /**
     * @return A URL pointing to an image file that represents your client application.
     */
    @JsonProperty("icon_url")
    public Optional<String> getIconUrl() {
        return iconUrl;
    }

    /**
     * @return OIDC discovery URL of the trusted OIDC provider associated with the SAML IdP. Triggers auto-discovery of the OIDC metadata used to validate ID-JAGs for cross-app access.
     */
    @JsonProperty("discovery_url")
    public Optional<String> getDiscoveryUrl() {
        return discoveryUrl;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof IdpSamlpOptionsRequestMetadataUrl && equalTo((IdpSamlpOptionsRequestMetadataUrl) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(IdpSamlpOptionsRequestMetadataUrl other) {
        return metadataUrl.equals(other.metadataUrl)
                && signSamlRequest == other.signSamlRequest
                && signatureAlgorithm.equals(other.signatureAlgorithm)
                && digestAlgorithm.equals(other.digestAlgorithm)
                && protocolBinding.equals(other.protocolBinding)
                && bindingMethod.equals(other.bindingMethod)
                && signingCert.equals(other.signingCert)
                && idpInitiated.equals(other.idpInitiated)
                && iconUrl.equals(other.iconUrl)
                && discoveryUrl.equals(other.discoveryUrl);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.metadataUrl,
                this.signSamlRequest,
                this.signatureAlgorithm,
                this.digestAlgorithm,
                this.protocolBinding,
                this.bindingMethod,
                this.signingCert,
                this.idpInitiated,
                this.iconUrl,
                this.discoveryUrl);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static MetadataUrlStage builder() {
        return new Builder();
    }

    public interface MetadataUrlStage {
        /**
         * <p>URL provided by SAML provider which returns information used for creating the connection</p>
         */
        SignSamlRequestStage metadataUrl(@NotNull String metadataUrl);

        Builder from(IdpSamlpOptionsRequestMetadataUrl other);
    }

    public interface SignSamlRequestStage {
        /**
         * <p>When enabled, the SAML authentication request will be signed.</p>
         */
        _FinalStage signSamlRequest(boolean signSamlRequest);
    }

    public interface _FinalStage {
        IdpSamlpOptionsRequestMetadataUrl build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage signatureAlgorithm(Optional<IdpSignAlgTypeEnum> signatureAlgorithm);

        _FinalStage signatureAlgorithm(IdpSignAlgTypeEnum signatureAlgorithm);

        _FinalStage digestAlgorithm(Optional<IdpSignAlgDigestTypeEnum> digestAlgorithm);

        _FinalStage digestAlgorithm(IdpSignAlgDigestTypeEnum digestAlgorithm);

        _FinalStage protocolBinding(Optional<IdpProtocolBindingTypeEnum> protocolBinding);

        _FinalStage protocolBinding(IdpProtocolBindingTypeEnum protocolBinding);

        /**
         * <p>Defines the specific HTTP binding used for sending SAML messages.</p>
         */
        _FinalStage bindingMethod(Optional<String> bindingMethod);

        _FinalStage bindingMethod(String bindingMethod);

        /**
         * <p>Signing certificate (encoded in PEM or CER) you retrieved from the IdP. Optional for this variant: when omitted, the certificate is read from the metadata document.</p>
         */
        _FinalStage signingCert(Optional<String> signingCert);

        _FinalStage signingCert(String signingCert);

        _FinalStage idpInitiated(Optional<IdpOptionsIdpInitiated> idpInitiated);

        _FinalStage idpInitiated(IdpOptionsIdpInitiated idpInitiated);

        /**
         * <p>A URL pointing to an image file that represents your client application.</p>
         */
        _FinalStage iconUrl(Optional<String> iconUrl);

        _FinalStage iconUrl(String iconUrl);

        /**
         * <p>OIDC discovery URL of the trusted OIDC provider associated with the SAML IdP. Triggers auto-discovery of the OIDC metadata used to validate ID-JAGs for cross-app access.</p>
         */
        _FinalStage discoveryUrl(Optional<String> discoveryUrl);

        _FinalStage discoveryUrl(String discoveryUrl);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements MetadataUrlStage, SignSamlRequestStage, _FinalStage {
        private String metadataUrl;

        private boolean signSamlRequest;

        private Optional<String> discoveryUrl = Optional.empty();

        private Optional<String> iconUrl = Optional.empty();

        private Optional<IdpOptionsIdpInitiated> idpInitiated = Optional.empty();

        private Optional<String> signingCert = Optional.empty();

        private Optional<String> bindingMethod = Optional.empty();

        private Optional<IdpProtocolBindingTypeEnum> protocolBinding = Optional.empty();

        private Optional<IdpSignAlgDigestTypeEnum> digestAlgorithm = Optional.empty();

        private Optional<IdpSignAlgTypeEnum> signatureAlgorithm = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(IdpSamlpOptionsRequestMetadataUrl other) {
            metadataUrl(other.getMetadataUrl());
            signSamlRequest(other.getSignSamlRequest());
            signatureAlgorithm(other.getSignatureAlgorithm());
            digestAlgorithm(other.getDigestAlgorithm());
            protocolBinding(other.getProtocolBinding());
            bindingMethod(other.getBindingMethod());
            signingCert(other.getSigningCert());
            idpInitiated(other.getIdpInitiated());
            iconUrl(other.getIconUrl());
            discoveryUrl(other.getDiscoveryUrl());
            return this;
        }

        /**
         * <p>URL provided by SAML provider which returns information used for creating the connection</p>
         * <p>URL provided by SAML provider which returns information used for creating the connection</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("metadataUrl")
        public SignSamlRequestStage metadataUrl(@NotNull String metadataUrl) {
            this.metadataUrl = Objects.requireNonNull(metadataUrl, "metadataUrl must not be null");
            return this;
        }

        /**
         * <p>When enabled, the SAML authentication request will be signed.</p>
         * <p>When enabled, the SAML authentication request will be signed.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("signSAMLRequest")
        public _FinalStage signSamlRequest(boolean signSamlRequest) {
            this.signSamlRequest = signSamlRequest;
            return this;
        }

        /**
         * <p>OIDC discovery URL of the trusted OIDC provider associated with the SAML IdP. Triggers auto-discovery of the OIDC metadata used to validate ID-JAGs for cross-app access.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage discoveryUrl(String discoveryUrl) {
            this.discoveryUrl = Optional.ofNullable(discoveryUrl);
            return this;
        }

        /**
         * <p>OIDC discovery URL of the trusted OIDC provider associated with the SAML IdP. Triggers auto-discovery of the OIDC metadata used to validate ID-JAGs for cross-app access.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "discovery_url", nulls = Nulls.SKIP)
        public _FinalStage discoveryUrl(Optional<String> discoveryUrl) {
            this.discoveryUrl = discoveryUrl;
            return this;
        }

        /**
         * <p>A URL pointing to an image file that represents your client application.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage iconUrl(String iconUrl) {
            this.iconUrl = Optional.ofNullable(iconUrl);
            return this;
        }

        /**
         * <p>A URL pointing to an image file that represents your client application.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "icon_url", nulls = Nulls.SKIP)
        public _FinalStage iconUrl(Optional<String> iconUrl) {
            this.iconUrl = iconUrl;
            return this;
        }

        @java.lang.Override
        public _FinalStage idpInitiated(IdpOptionsIdpInitiated idpInitiated) {
            this.idpInitiated = Optional.ofNullable(idpInitiated);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "idpInitiated", nulls = Nulls.SKIP)
        public _FinalStage idpInitiated(Optional<IdpOptionsIdpInitiated> idpInitiated) {
            this.idpInitiated = idpInitiated;
            return this;
        }

        /**
         * <p>Signing certificate (encoded in PEM or CER) you retrieved from the IdP. Optional for this variant: when omitted, the certificate is read from the metadata document.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage signingCert(String signingCert) {
            this.signingCert = Optional.ofNullable(signingCert);
            return this;
        }

        /**
         * <p>Signing certificate (encoded in PEM or CER) you retrieved from the IdP. Optional for this variant: when omitted, the certificate is read from the metadata document.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "signingCert", nulls = Nulls.SKIP)
        public _FinalStage signingCert(Optional<String> signingCert) {
            this.signingCert = signingCert;
            return this;
        }

        /**
         * <p>Defines the specific HTTP binding used for sending SAML messages.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage bindingMethod(String bindingMethod) {
            this.bindingMethod = Optional.ofNullable(bindingMethod);
            return this;
        }

        /**
         * <p>Defines the specific HTTP binding used for sending SAML messages.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "bindingMethod", nulls = Nulls.SKIP)
        public _FinalStage bindingMethod(Optional<String> bindingMethod) {
            this.bindingMethod = bindingMethod;
            return this;
        }

        @java.lang.Override
        public _FinalStage protocolBinding(IdpProtocolBindingTypeEnum protocolBinding) {
            this.protocolBinding = Optional.ofNullable(protocolBinding);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "protocolBinding", nulls = Nulls.SKIP)
        public _FinalStage protocolBinding(Optional<IdpProtocolBindingTypeEnum> protocolBinding) {
            this.protocolBinding = protocolBinding;
            return this;
        }

        @java.lang.Override
        public _FinalStage digestAlgorithm(IdpSignAlgDigestTypeEnum digestAlgorithm) {
            this.digestAlgorithm = Optional.ofNullable(digestAlgorithm);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "digestAlgorithm", nulls = Nulls.SKIP)
        public _FinalStage digestAlgorithm(Optional<IdpSignAlgDigestTypeEnum> digestAlgorithm) {
            this.digestAlgorithm = digestAlgorithm;
            return this;
        }

        @java.lang.Override
        public _FinalStage signatureAlgorithm(IdpSignAlgTypeEnum signatureAlgorithm) {
            this.signatureAlgorithm = Optional.ofNullable(signatureAlgorithm);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "signatureAlgorithm", nulls = Nulls.SKIP)
        public _FinalStage signatureAlgorithm(Optional<IdpSignAlgTypeEnum> signatureAlgorithm) {
            this.signatureAlgorithm = signatureAlgorithm;
            return this;
        }

        @java.lang.Override
        public IdpSamlpOptionsRequestMetadataUrl build() {
            return new IdpSamlpOptionsRequestMetadataUrl(
                    metadataUrl,
                    signSamlRequest,
                    signatureAlgorithm,
                    digestAlgorithm,
                    protocolBinding,
                    bindingMethod,
                    signingCert,
                    idpInitiated,
                    iconUrl,
                    discoveryUrl,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
