/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class IdpSignAlgTypeEnum {
    public static final IdpSignAlgTypeEnum RSA_SHA1 = new IdpSignAlgTypeEnum(Value.RSA_SHA1, "rsa-sha1");

    public static final IdpSignAlgTypeEnum RSA_SHA256 = new IdpSignAlgTypeEnum(Value.RSA_SHA256, "rsa-sha256");

    private final Value value;

    private final String string;

    IdpSignAlgTypeEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof IdpSignAlgTypeEnum && this.string.equals(((IdpSignAlgTypeEnum) other).string));
    }

    @Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case RSA_SHA1:
                return visitor.visitRsaSha1();
            case RSA_SHA256:
                return visitor.visitRsaSha256();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static IdpSignAlgTypeEnum valueOf(String value) {
        switch (value) {
            case "rsa-sha1":
                return RSA_SHA1;
            case "rsa-sha256":
                return RSA_SHA256;
            default:
                return new IdpSignAlgTypeEnum(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        RSA_SHA256,

        RSA_SHA1,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitRsaSha256();

        T visitRsaSha1();

        T visitUnknown(String unknownType);
    }
}
