/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.auth0.client.myorganization.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import java.io.IOException;
import java.util.Objects;

@JsonDeserialize(using = IdpUpdateKnownResponse.Deserializer.class)
public final class IdpUpdateKnownResponse {
    private final Object value;

    private final int type;

    private IdpUpdateKnownResponse(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    @SuppressWarnings("unchecked")
    public <T> T visit(Visitor<T> visitor) {
        if (this.type == 0) {
            return visitor.visit((IdpAdfsResponse) this.value);
        } else if (this.type == 1) {
            return visitor.visit((IdpGoogleAppsResponse) this.value);
        } else if (this.type == 2) {
            return visitor.visit((IdpOidcResponse) this.value);
        } else if (this.type == 3) {
            return visitor.visit((IdpOktaResponse) this.value);
        } else if (this.type == 4) {
            return visitor.visit((IdpPingFederateResponse) this.value);
        } else if (this.type == 5) {
            return visitor.visit((IdpSamlpResponse) this.value);
        } else if (this.type == 6) {
            return visitor.visit((IdpWaadResponse) this.value);
        }
        throw new IllegalStateException("Failed to visit value. This should never happen.");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof IdpUpdateKnownResponse && equalTo((IdpUpdateKnownResponse) other);
    }

    private boolean equalTo(IdpUpdateKnownResponse other) {
        return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
        return this.value.toString();
    }

    public static IdpUpdateKnownResponse of(IdpAdfsResponse value) {
        return new IdpUpdateKnownResponse(value, 0);
    }

    public static IdpUpdateKnownResponse of(IdpGoogleAppsResponse value) {
        return new IdpUpdateKnownResponse(value, 1);
    }

    public static IdpUpdateKnownResponse of(IdpOidcResponse value) {
        return new IdpUpdateKnownResponse(value, 2);
    }

    public static IdpUpdateKnownResponse of(IdpOktaResponse value) {
        return new IdpUpdateKnownResponse(value, 3);
    }

    public static IdpUpdateKnownResponse of(IdpPingFederateResponse value) {
        return new IdpUpdateKnownResponse(value, 4);
    }

    public static IdpUpdateKnownResponse of(IdpSamlpResponse value) {
        return new IdpUpdateKnownResponse(value, 5);
    }

    public static IdpUpdateKnownResponse of(IdpWaadResponse value) {
        return new IdpUpdateKnownResponse(value, 6);
    }

    public interface Visitor<T> {
        T visit(IdpAdfsResponse value);

        T visit(IdpGoogleAppsResponse value);

        T visit(IdpOidcResponse value);

        T visit(IdpOktaResponse value);

        T visit(IdpPingFederateResponse value);

        T visit(IdpSamlpResponse value);

        T visit(IdpWaadResponse value);
    }

    static final class Deserializer extends StdDeserializer<IdpUpdateKnownResponse> {
        Deserializer() {
            super(IdpUpdateKnownResponse.class);
        }

        @java.lang.Override
        public IdpUpdateKnownResponse deserialize(JsonParser p, DeserializationContext context) throws IOException {
            Object value = p.readValueAs(Object.class);
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, IdpAdfsResponse.class));
            } catch (RuntimeException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, IdpGoogleAppsResponse.class));
            } catch (RuntimeException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, IdpOidcResponse.class));
            } catch (RuntimeException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, IdpOktaResponse.class));
            } catch (RuntimeException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, IdpPingFederateResponse.class));
            } catch (RuntimeException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, IdpSamlpResponse.class));
            } catch (RuntimeException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, IdpWaadResponse.class));
            } catch (RuntimeException e) {
            }
            throw new JsonParseException(p, "Failed to deserialize");
        }
    }
}
