/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import java.util.List;

public interface IIdpProvisioningConfig {
    String getIdentityProviderId();

    String getIdentityProviderName();

    IdpStrategyEnum getStrategy();

    IdpProvisioningMethodEnum getMethod();

    List<IdpProvisioningUserAttributeMapItem> getAttributes();

    String getUserIdAttribute();
}
