/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;

public interface IIdpScimTokenBase {
    String getTokenId();

    Optional<List<String>> getScopes();

    OffsetDateTime getCreatedAt();

    Optional<OffsetDateTime> getValidUntil();
}
