/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.auth0.client.myorganization.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListIdentityProvidersResponseContent.Builder.class)
public final class ListIdentityProvidersResponseContent {
    private final Optional<List<IdpKnownResponse>> identityProviders;

    private final Map<String, Object> additionalProperties;

    private ListIdentityProvidersResponseContent(
            Optional<List<IdpKnownResponse>> identityProviders, Map<String, Object> additionalProperties) {
        this.identityProviders = identityProviders;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("identity_providers")
    public Optional<List<IdpKnownResponse>> getIdentityProviders() {
        return identityProviders;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListIdentityProvidersResponseContent
                && equalTo((ListIdentityProvidersResponseContent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListIdentityProvidersResponseContent other) {
        return identityProviders.equals(other.identityProviders);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.identityProviders);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<IdpKnownResponse>> identityProviders = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListIdentityProvidersResponseContent other) {
            identityProviders(other.getIdentityProviders());
            return this;
        }

        @JsonSetter(value = "identity_providers", nulls = Nulls.SKIP)
        public Builder identityProviders(Optional<List<IdpKnownResponse>> identityProviders) {
            this.identityProviders = identityProviders;
            return this;
        }

        public Builder identityProviders(List<IdpKnownResponse> identityProviders) {
            this.identityProviders = Optional.ofNullable(identityProviders);
            return this;
        }

        public ListIdentityProvidersResponseContent build() {
            return new ListIdentityProvidersResponseContent(identityProviders, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
