/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.auth0.client.myorganization.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListRolesResponseContent.Builder.class)
public final class ListRolesResponseContent {
    private final List<Role> roles;

    private final Optional<String> next;

    private final Map<String, Object> additionalProperties;

    private ListRolesResponseContent(
            List<Role> roles, Optional<String> next, Map<String, Object> additionalProperties) {
        this.roles = roles;
        this.next = next;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("roles")
    public List<Role> getRoles() {
        return roles;
    }

    /**
     * @return Pagination cursor for the next page of results
     */
    @JsonProperty("next")
    public Optional<String> getNext() {
        return next;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListRolesResponseContent && equalTo((ListRolesResponseContent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListRolesResponseContent other) {
        return roles.equals(other.roles) && next.equals(other.next);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.roles, this.next);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private List<Role> roles = new ArrayList<>();

        private Optional<String> next = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListRolesResponseContent other) {
            roles(other.getRoles());
            next(other.getNext());
            return this;
        }

        @JsonSetter(value = "roles", nulls = Nulls.SKIP)
        public Builder roles(List<Role> roles) {
            this.roles.clear();
            if (roles != null) {
                this.roles.addAll(roles);
            }
            return this;
        }

        public Builder addRoles(Role roles) {
            this.roles.add(roles);
            return this;
        }

        public Builder addAllRoles(List<Role> roles) {
            if (roles != null) {
                this.roles.addAll(roles);
            }
            return this;
        }

        /**
         * <p>Pagination cursor for the next page of results</p>
         */
        @JsonSetter(value = "next", nulls = Nulls.SKIP)
        public Builder next(Optional<String> next) {
            this.next = next;
            return this;
        }

        public Builder next(String next) {
            this.next = Optional.ofNullable(next);
            return this;
        }

        public ListRolesResponseContent build() {
            return new ListRolesResponseContent(roles, next, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
