/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.auth0.client.myorganization.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListMembersInvitationsResponseContent.Builder.class)
public final class ListMembersInvitationsResponseContent {
    private final Optional<String> next;

    private final Optional<Integer> total;

    private final Optional<Boolean> totalIsCapped;

    private final Optional<List<MemberInvitation>> invitations;

    private final Map<String, Object> additionalProperties;

    private ListMembersInvitationsResponseContent(
            Optional<String> next,
            Optional<Integer> total,
            Optional<Boolean> totalIsCapped,
            Optional<List<MemberInvitation>> invitations,
            Map<String, Object> additionalProperties) {
        this.next = next;
        this.total = total;
        this.totalIsCapped = totalIsCapped;
        this.invitations = invitations;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Pagination cursor for the next page of results.
     */
    @JsonProperty("next")
    public Optional<String> getNext() {
        return next;
    }

    /**
     * @return Best-effort count of pending invitations in the result set (reflecting any active filters). Only present when include_totals=true. Capped at 1000.
     */
    @JsonProperty("total")
    public Optional<Integer> getTotal() {
        return total;
    }

    /**
     * @return Whether counting stopped before reaching the true size of the result set. When true, 'total' is a lower bound (the true size is 'total' or greater); when false, 'total' reflects the full result set as counted. Only present when 'total' is present.
     */
    @JsonProperty("total_is_capped")
    public Optional<Boolean> getTotalIsCapped() {
        return totalIsCapped;
    }

    @JsonProperty("invitations")
    public Optional<List<MemberInvitation>> getInvitations() {
        return invitations;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListMembersInvitationsResponseContent
                && equalTo((ListMembersInvitationsResponseContent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListMembersInvitationsResponseContent other) {
        return next.equals(other.next)
                && total.equals(other.total)
                && totalIsCapped.equals(other.totalIsCapped)
                && invitations.equals(other.invitations);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.next, this.total, this.totalIsCapped, this.invitations);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> next = Optional.empty();

        private Optional<Integer> total = Optional.empty();

        private Optional<Boolean> totalIsCapped = Optional.empty();

        private Optional<List<MemberInvitation>> invitations = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListMembersInvitationsResponseContent other) {
            next(other.getNext());
            total(other.getTotal());
            totalIsCapped(other.getTotalIsCapped());
            invitations(other.getInvitations());
            return this;
        }

        /**
         * <p>Pagination cursor for the next page of results.</p>
         */
        @JsonSetter(value = "next", nulls = Nulls.SKIP)
        public Builder next(Optional<String> next) {
            this.next = next;
            return this;
        }

        public Builder next(String next) {
            this.next = Optional.ofNullable(next);
            return this;
        }

        /**
         * <p>Best-effort count of pending invitations in the result set (reflecting any active filters). Only present when include_totals=true. Capped at 1000.</p>
         */
        @JsonSetter(value = "total", nulls = Nulls.SKIP)
        public Builder total(Optional<Integer> total) {
            this.total = total;
            return this;
        }

        public Builder total(Integer total) {
            this.total = Optional.ofNullable(total);
            return this;
        }

        /**
         * <p>Whether counting stopped before reaching the true size of the result set. When true, 'total' is a lower bound (the true size is 'total' or greater); when false, 'total' reflects the full result set as counted. Only present when 'total' is present.</p>
         */
        @JsonSetter(value = "total_is_capped", nulls = Nulls.SKIP)
        public Builder totalIsCapped(Optional<Boolean> totalIsCapped) {
            this.totalIsCapped = totalIsCapped;
            return this;
        }

        public Builder totalIsCapped(Boolean totalIsCapped) {
            this.totalIsCapped = Optional.ofNullable(totalIsCapped);
            return this;
        }

        @JsonSetter(value = "invitations", nulls = Nulls.SKIP)
        public Builder invitations(Optional<List<MemberInvitation>> invitations) {
            this.invitations = invitations;
            return this;
        }

        public Builder invitations(List<MemberInvitation> invitations) {
            this.invitations = Optional.ofNullable(invitations);
            return this;
        }

        public ListMembersInvitationsResponseContent build() {
            return new ListMembersInvitationsResponseContent(
                    next, total, totalIsCapped, invitations, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
