/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.auth0.client.myorganization.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListUserStoresResponseContent.Builder.class)
public final class ListUserStoresResponseContent {
    private final List<UserStore> userStores;

    private final Map<String, Object> additionalProperties;

    private ListUserStoresResponseContent(List<UserStore> userStores, Map<String, Object> additionalProperties) {
        this.userStores = userStores;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("user_stores")
    public List<UserStore> getUserStores() {
        return userStores;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListUserStoresResponseContent && equalTo((ListUserStoresResponseContent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListUserStoresResponseContent other) {
        return userStores.equals(other.userStores);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.userStores);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private List<UserStore> userStores = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListUserStoresResponseContent other) {
            userStores(other.getUserStores());
            return this;
        }

        @JsonSetter(value = "user_stores", nulls = Nulls.SKIP)
        public Builder userStores(List<UserStore> userStores) {
            this.userStores.clear();
            if (userStores != null) {
                this.userStores.addAll(userStores);
            }
            return this;
        }

        public Builder addUserStores(UserStore userStores) {
            this.userStores.add(userStores);
            return this;
        }

        public Builder addAllUserStores(List<UserStore> userStores) {
            if (userStores != null) {
                this.userStores.addAll(userStores);
            }
            return this;
        }

        public ListUserStoresResponseContent build() {
            return new ListUserStoresResponseContent(userStores, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
