/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.auth0.client.myorganization.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = MemberInvitation.Builder.class)
public final class MemberInvitation {
    private final Optional<String> id;

    private final Optional<String> organizationId;

    private final Optional<MemberInvitationInviter> inviter;

    private final Optional<MemberInvitationInvitee> invitee;

    private final Optional<String> identityProviderId;

    private final Optional<OffsetDateTime> createdAt;

    private final Optional<OffsetDateTime> expiresAt;

    private final Optional<List<String>> roles;

    private final Optional<String> invitationUrl;

    private final Optional<String> ticketId;

    private final Map<String, Object> additionalProperties;

    private MemberInvitation(
            Optional<String> id,
            Optional<String> organizationId,
            Optional<MemberInvitationInviter> inviter,
            Optional<MemberInvitationInvitee> invitee,
            Optional<String> identityProviderId,
            Optional<OffsetDateTime> createdAt,
            Optional<OffsetDateTime> expiresAt,
            Optional<List<String>> roles,
            Optional<String> invitationUrl,
            Optional<String> ticketId,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.organizationId = organizationId;
        this.inviter = inviter;
        this.invitee = invitee;
        this.identityProviderId = identityProviderId;
        this.createdAt = createdAt;
        this.expiresAt = expiresAt;
        this.roles = roles;
        this.invitationUrl = invitationUrl;
        this.ticketId = ticketId;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("id")
    public Optional<String> getId() {
        return id;
    }

    @JsonProperty("organization_id")
    public Optional<String> getOrganizationId() {
        return organizationId;
    }

    @JsonProperty("inviter")
    public Optional<MemberInvitationInviter> getInviter() {
        return inviter;
    }

    @JsonProperty("invitee")
    public Optional<MemberInvitationInvitee> getInvitee() {
        return invitee;
    }

    @JsonProperty("identity_provider_id")
    public Optional<String> getIdentityProviderId() {
        return identityProviderId;
    }

    /**
     * @return The ISO 8601 formatted timestamp representing the creation time of the invitation.
     */
    @JsonProperty("created_at")
    public Optional<OffsetDateTime> getCreatedAt() {
        return createdAt;
    }

    /**
     * @return The ISO 8601 formatted timestamp representing the expiration time of the invitation.
     */
    @JsonProperty("expires_at")
    public Optional<OffsetDateTime> getExpiresAt() {
        return expiresAt;
    }

    @JsonProperty("roles")
    public Optional<List<String>> getRoles() {
        return roles;
    }

    /**
     * @return The invitation url to be sent to the invitee.
     */
    @JsonProperty("invitation_url")
    public Optional<String> getInvitationUrl() {
        return invitationUrl;
    }

    /**
     * @return The ID of the invitation ticket.
     */
    @JsonProperty("ticket_id")
    public Optional<String> getTicketId() {
        return ticketId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof MemberInvitation && equalTo((MemberInvitation) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(MemberInvitation other) {
        return id.equals(other.id)
                && organizationId.equals(other.organizationId)
                && inviter.equals(other.inviter)
                && invitee.equals(other.invitee)
                && identityProviderId.equals(other.identityProviderId)
                && createdAt.equals(other.createdAt)
                && expiresAt.equals(other.expiresAt)
                && roles.equals(other.roles)
                && invitationUrl.equals(other.invitationUrl)
                && ticketId.equals(other.ticketId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.id,
                this.organizationId,
                this.inviter,
                this.invitee,
                this.identityProviderId,
                this.createdAt,
                this.expiresAt,
                this.roles,
                this.invitationUrl,
                this.ticketId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> id = Optional.empty();

        private Optional<String> organizationId = Optional.empty();

        private Optional<MemberInvitationInviter> inviter = Optional.empty();

        private Optional<MemberInvitationInvitee> invitee = Optional.empty();

        private Optional<String> identityProviderId = Optional.empty();

        private Optional<OffsetDateTime> createdAt = Optional.empty();

        private Optional<OffsetDateTime> expiresAt = Optional.empty();

        private Optional<List<String>> roles = Optional.empty();

        private Optional<String> invitationUrl = Optional.empty();

        private Optional<String> ticketId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(MemberInvitation other) {
            id(other.getId());
            organizationId(other.getOrganizationId());
            inviter(other.getInviter());
            invitee(other.getInvitee());
            identityProviderId(other.getIdentityProviderId());
            createdAt(other.getCreatedAt());
            expiresAt(other.getExpiresAt());
            roles(other.getRoles());
            invitationUrl(other.getInvitationUrl());
            ticketId(other.getTicketId());
            return this;
        }

        @JsonSetter(value = "id", nulls = Nulls.SKIP)
        public Builder id(Optional<String> id) {
            this.id = id;
            return this;
        }

        public Builder id(String id) {
            this.id = Optional.ofNullable(id);
            return this;
        }

        @JsonSetter(value = "organization_id", nulls = Nulls.SKIP)
        public Builder organizationId(Optional<String> organizationId) {
            this.organizationId = organizationId;
            return this;
        }

        public Builder organizationId(String organizationId) {
            this.organizationId = Optional.ofNullable(organizationId);
            return this;
        }

        @JsonSetter(value = "inviter", nulls = Nulls.SKIP)
        public Builder inviter(Optional<MemberInvitationInviter> inviter) {
            this.inviter = inviter;
            return this;
        }

        public Builder inviter(MemberInvitationInviter inviter) {
            this.inviter = Optional.ofNullable(inviter);
            return this;
        }

        @JsonSetter(value = "invitee", nulls = Nulls.SKIP)
        public Builder invitee(Optional<MemberInvitationInvitee> invitee) {
            this.invitee = invitee;
            return this;
        }

        public Builder invitee(MemberInvitationInvitee invitee) {
            this.invitee = Optional.ofNullable(invitee);
            return this;
        }

        @JsonSetter(value = "identity_provider_id", nulls = Nulls.SKIP)
        public Builder identityProviderId(Optional<String> identityProviderId) {
            this.identityProviderId = identityProviderId;
            return this;
        }

        public Builder identityProviderId(String identityProviderId) {
            this.identityProviderId = Optional.ofNullable(identityProviderId);
            return this;
        }

        /**
         * <p>The ISO 8601 formatted timestamp representing the creation time of the invitation.</p>
         */
        @JsonSetter(value = "created_at", nulls = Nulls.SKIP)
        public Builder createdAt(Optional<OffsetDateTime> createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        public Builder createdAt(OffsetDateTime createdAt) {
            this.createdAt = Optional.ofNullable(createdAt);
            return this;
        }

        /**
         * <p>The ISO 8601 formatted timestamp representing the expiration time of the invitation.</p>
         */
        @JsonSetter(value = "expires_at", nulls = Nulls.SKIP)
        public Builder expiresAt(Optional<OffsetDateTime> expiresAt) {
            this.expiresAt = expiresAt;
            return this;
        }

        public Builder expiresAt(OffsetDateTime expiresAt) {
            this.expiresAt = Optional.ofNullable(expiresAt);
            return this;
        }

        @JsonSetter(value = "roles", nulls = Nulls.SKIP)
        public Builder roles(Optional<List<String>> roles) {
            this.roles = roles;
            return this;
        }

        public Builder roles(List<String> roles) {
            this.roles = Optional.ofNullable(roles);
            return this;
        }

        /**
         * <p>The invitation url to be sent to the invitee.</p>
         */
        @JsonSetter(value = "invitation_url", nulls = Nulls.SKIP)
        public Builder invitationUrl(Optional<String> invitationUrl) {
            this.invitationUrl = invitationUrl;
            return this;
        }

        public Builder invitationUrl(String invitationUrl) {
            this.invitationUrl = Optional.ofNullable(invitationUrl);
            return this;
        }

        /**
         * <p>The ID of the invitation ticket.</p>
         */
        @JsonSetter(value = "ticket_id", nulls = Nulls.SKIP)
        public Builder ticketId(Optional<String> ticketId) {
            this.ticketId = ticketId;
            return this;
        }

        public Builder ticketId(String ticketId) {
            this.ticketId = Optional.ofNullable(ticketId);
            return this;
        }

        public MemberInvitation build() {
            return new MemberInvitation(
                    id,
                    organizationId,
                    inviter,
                    invitee,
                    identityProviderId,
                    createdAt,
                    expiresAt,
                    roles,
                    invitationUrl,
                    ticketId,
                    additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
