/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class OrgDomainStatusEnum {
    public static final OrgDomainStatusEnum FAILED = new OrgDomainStatusEnum(Value.FAILED, "failed");

    public static final OrgDomainStatusEnum PENDING = new OrgDomainStatusEnum(Value.PENDING, "pending");

    public static final OrgDomainStatusEnum VERIFIED = new OrgDomainStatusEnum(Value.VERIFIED, "verified");

    private final Value value;

    private final String string;

    OrgDomainStatusEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof OrgDomainStatusEnum && this.string.equals(((OrgDomainStatusEnum) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case FAILED:
                return visitor.visitFailed();
            case PENDING:
                return visitor.visitPending();
            case VERIFIED:
                return visitor.visitVerified();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static OrgDomainStatusEnum valueOf(String value) {
        switch (value) {
            case "failed":
                return FAILED;
            case "pending":
                return PENDING;
            case "verified":
                return VERIFIED;
            default:
                return new OrgDomainStatusEnum(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        FAILED,

        PENDING,

        VERIFIED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitFailed();

        T visitPending();

        T visitVerified();

        T visitUnknown(String unknownType);
    }
}
