/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.auth0.client.myorganization.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = OrgDetails.Builder.class)
public final class OrgDetails {
    private final Optional<String> name;

    private final Optional<String> displayName;

    private final Optional<OrgBranding> branding;

    private final Map<String, Object> additionalProperties;

    private OrgDetails(
            Optional<String> name,
            Optional<String> displayName,
            Optional<OrgBranding> branding,
            Map<String, Object> additionalProperties) {
        this.name = name;
        this.displayName = displayName;
        this.branding = branding;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The name of this organization.
     */
    @JsonProperty("name")
    public Optional<String> getName() {
        return name;
    }

    /**
     * @return Friendly name of this organization.
     */
    @JsonProperty("display_name")
    public Optional<String> getDisplayName() {
        return displayName;
    }

    @JsonProperty("branding")
    public Optional<OrgBranding> getBranding() {
        return branding;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof OrgDetails && equalTo((OrgDetails) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(OrgDetails other) {
        return name.equals(other.name) && displayName.equals(other.displayName) && branding.equals(other.branding);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.name, this.displayName, this.branding);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> name = Optional.empty();

        private Optional<String> displayName = Optional.empty();

        private Optional<OrgBranding> branding = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(OrgDetails other) {
            name(other.getName());
            displayName(other.getDisplayName());
            branding(other.getBranding());
            return this;
        }

        /**
         * <p>The name of this organization.</p>
         */
        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public Builder name(Optional<String> name) {
            this.name = name;
            return this;
        }

        public Builder name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        /**
         * <p>Friendly name of this organization.</p>
         */
        @JsonSetter(value = "display_name", nulls = Nulls.SKIP)
        public Builder displayName(Optional<String> displayName) {
            this.displayName = displayName;
            return this;
        }

        public Builder displayName(String displayName) {
            this.displayName = Optional.ofNullable(displayName);
            return this;
        }

        @JsonSetter(value = "branding", nulls = Nulls.SKIP)
        public Builder branding(Optional<OrgBranding> branding) {
            this.branding = branding;
            return this;
        }

        public Builder branding(OrgBranding branding) {
            this.branding = Optional.ofNullable(branding);
            return this;
        }

        public OrgDetails build() {
            return new OrgDetails(name, displayName, branding, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
