/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.auth0.client.myorganization.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = OrgDomain.Builder.class)
public final class OrgDomain {
    private final String id;

    private final String orgId;

    private final String domain;

    private final OrgDomainStatusEnum status;

    private final String verificationTxt;

    private final String verificationHost;

    private final Map<String, Object> additionalProperties;

    private OrgDomain(
            String id,
            String orgId,
            String domain,
            OrgDomainStatusEnum status,
            String verificationTxt,
            String verificationHost,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.orgId = orgId;
        this.domain = domain;
        this.status = status;
        this.verificationTxt = verificationTxt;
        this.verificationHost = verificationHost;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("org_id")
    public String getOrgId() {
        return orgId;
    }

    @JsonProperty("domain")
    public String getDomain() {
        return domain;
    }

    @JsonProperty("status")
    public OrgDomainStatusEnum getStatus() {
        return status;
    }

    /**
     * @return Value used to verify the domain.
     */
    @JsonProperty("verification_txt")
    public String getVerificationTxt() {
        return verificationTxt;
    }

    /**
     * @return Stores the full domain where the TXT record should be added.
     */
    @JsonProperty("verification_host")
    public String getVerificationHost() {
        return verificationHost;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof OrgDomain && equalTo((OrgDomain) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(OrgDomain other) {
        return id.equals(other.id)
                && orgId.equals(other.orgId)
                && domain.equals(other.domain)
                && status.equals(other.status)
                && verificationTxt.equals(other.verificationTxt)
                && verificationHost.equals(other.verificationHost);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.orgId, this.domain, this.status, this.verificationTxt, this.verificationHost);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        OrgIdStage id(@NotNull String id);

        Builder from(OrgDomain other);
    }

    public interface OrgIdStage {
        DomainStage orgId(@NotNull String orgId);
    }

    public interface DomainStage {
        StatusStage domain(@NotNull String domain);
    }

    public interface StatusStage {
        VerificationTxtStage status(@NotNull OrgDomainStatusEnum status);
    }

    public interface VerificationTxtStage {
        /**
         * <p>Value used to verify the domain.</p>
         */
        VerificationHostStage verificationTxt(@NotNull String verificationTxt);
    }

    public interface VerificationHostStage {
        /**
         * <p>Stores the full domain where the TXT record should be added.</p>
         */
        _FinalStage verificationHost(@NotNull String verificationHost);
    }

    public interface _FinalStage {
        OrgDomain build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements IdStage,
                    OrgIdStage,
                    DomainStage,
                    StatusStage,
                    VerificationTxtStage,
                    VerificationHostStage,
                    _FinalStage {
        private String id;

        private String orgId;

        private String domain;

        private OrgDomainStatusEnum status;

        private String verificationTxt;

        private String verificationHost;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(OrgDomain other) {
            id(other.getId());
            orgId(other.getOrgId());
            domain(other.getDomain());
            status(other.getStatus());
            verificationTxt(other.getVerificationTxt());
            verificationHost(other.getVerificationHost());
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public OrgIdStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("org_id")
        public DomainStage orgId(@NotNull String orgId) {
            this.orgId = Objects.requireNonNull(orgId, "orgId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("domain")
        public StatusStage domain(@NotNull String domain) {
            this.domain = Objects.requireNonNull(domain, "domain must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("status")
        public VerificationTxtStage status(@NotNull OrgDomainStatusEnum status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        /**
         * <p>Value used to verify the domain.</p>
         * <p>Value used to verify the domain.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("verification_txt")
        public VerificationHostStage verificationTxt(@NotNull String verificationTxt) {
            this.verificationTxt = Objects.requireNonNull(verificationTxt, "verificationTxt must not be null");
            return this;
        }

        /**
         * <p>Stores the full domain where the TXT record should be added.</p>
         * <p>Stores the full domain where the TXT record should be added.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("verification_host")
        public _FinalStage verificationHost(@NotNull String verificationHost) {
            this.verificationHost = Objects.requireNonNull(verificationHost, "verificationHost must not be null");
            return this;
        }

        @java.lang.Override
        public OrgDomain build() {
            return new OrgDomain(id, orgId, domain, status, verificationTxt, verificationHost, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
