/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.types;

import com.auth0.client.myorganization.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = OrgMember.Builder.class)
public final class OrgMember implements IUserAttributes {
    private final Optional<String> email;

    private final Optional<String> name;

    private final Optional<String> nickname;

    private final Optional<String> givenName;

    private final Optional<String> familyName;

    private final Optional<String> userId;

    private final Optional<List<OrgMemberRole>> roles;

    private final Optional<OffsetDateTime> createdAt;

    private final Optional<OffsetDateTime> updatedAt;

    private final Optional<OffsetDateTime> lastLogin;

    private final Map<String, Object> additionalProperties;

    private OrgMember(
            Optional<String> email,
            Optional<String> name,
            Optional<String> nickname,
            Optional<String> givenName,
            Optional<String> familyName,
            Optional<String> userId,
            Optional<List<OrgMemberRole>> roles,
            Optional<OffsetDateTime> createdAt,
            Optional<OffsetDateTime> updatedAt,
            Optional<OffsetDateTime> lastLogin,
            Map<String, Object> additionalProperties) {
        this.email = email;
        this.name = name;
        this.nickname = nickname;
        this.givenName = givenName;
        this.familyName = familyName;
        this.userId = userId;
        this.roles = roles;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.lastLogin = lastLogin;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Email
     */
    @JsonProperty("email")
    @java.lang.Override
    public Optional<String> getEmail() {
        return email;
    }

    /**
     * @return Full Name
     */
    @JsonProperty("name")
    @java.lang.Override
    public Optional<String> getName() {
        return name;
    }

    /**
     * @return User nickname
     */
    @JsonProperty("nickname")
    @java.lang.Override
    public Optional<String> getNickname() {
        return nickname;
    }

    /**
     * @return First name
     */
    @JsonProperty("given_name")
    @java.lang.Override
    public Optional<String> getGivenName() {
        return givenName;
    }

    /**
     * @return Last name
     */
    @JsonProperty("family_name")
    @java.lang.Override
    public Optional<String> getFamilyName() {
        return familyName;
    }

    @JsonProperty("user_id")
    public Optional<String> getUserId() {
        return userId;
    }

    @JsonProperty("roles")
    public Optional<List<OrgMemberRole>> getRoles() {
        return roles;
    }

    /**
     * @return Date and time when this user was created (ISO_8601 format).
     */
    @JsonProperty("created_at")
    public Optional<OffsetDateTime> getCreatedAt() {
        return createdAt;
    }

    /**
     * @return Date and time when this user was last updated (ISO_8601 format).
     */
    @JsonProperty("updated_at")
    public Optional<OffsetDateTime> getUpdatedAt() {
        return updatedAt;
    }

    /**
     * @return Last date and time this user logged in (ISO_8601 format).
     */
    @JsonProperty("last_login")
    public Optional<OffsetDateTime> getLastLogin() {
        return lastLogin;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof OrgMember && equalTo((OrgMember) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(OrgMember other) {
        return email.equals(other.email)
                && name.equals(other.name)
                && nickname.equals(other.nickname)
                && givenName.equals(other.givenName)
                && familyName.equals(other.familyName)
                && userId.equals(other.userId)
                && roles.equals(other.roles)
                && createdAt.equals(other.createdAt)
                && updatedAt.equals(other.updatedAt)
                && lastLogin.equals(other.lastLogin);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.email,
                this.name,
                this.nickname,
                this.givenName,
                this.familyName,
                this.userId,
                this.roles,
                this.createdAt,
                this.updatedAt,
                this.lastLogin);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> email = Optional.empty();

        private Optional<String> name = Optional.empty();

        private Optional<String> nickname = Optional.empty();

        private Optional<String> givenName = Optional.empty();

        private Optional<String> familyName = Optional.empty();

        private Optional<String> userId = Optional.empty();

        private Optional<List<OrgMemberRole>> roles = Optional.empty();

        private Optional<OffsetDateTime> createdAt = Optional.empty();

        private Optional<OffsetDateTime> updatedAt = Optional.empty();

        private Optional<OffsetDateTime> lastLogin = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(OrgMember other) {
            email(other.getEmail());
            name(other.getName());
            nickname(other.getNickname());
            givenName(other.getGivenName());
            familyName(other.getFamilyName());
            userId(other.getUserId());
            roles(other.getRoles());
            createdAt(other.getCreatedAt());
            updatedAt(other.getUpdatedAt());
            lastLogin(other.getLastLogin());
            return this;
        }

        /**
         * <p>Email</p>
         */
        @JsonSetter(value = "email", nulls = Nulls.SKIP)
        public Builder email(Optional<String> email) {
            this.email = email;
            return this;
        }

        public Builder email(String email) {
            this.email = Optional.ofNullable(email);
            return this;
        }

        /**
         * <p>Full Name</p>
         */
        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public Builder name(Optional<String> name) {
            this.name = name;
            return this;
        }

        public Builder name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        /**
         * <p>User nickname</p>
         */
        @JsonSetter(value = "nickname", nulls = Nulls.SKIP)
        public Builder nickname(Optional<String> nickname) {
            this.nickname = nickname;
            return this;
        }

        public Builder nickname(String nickname) {
            this.nickname = Optional.ofNullable(nickname);
            return this;
        }

        /**
         * <p>First name</p>
         */
        @JsonSetter(value = "given_name", nulls = Nulls.SKIP)
        public Builder givenName(Optional<String> givenName) {
            this.givenName = givenName;
            return this;
        }

        public Builder givenName(String givenName) {
            this.givenName = Optional.ofNullable(givenName);
            return this;
        }

        /**
         * <p>Last name</p>
         */
        @JsonSetter(value = "family_name", nulls = Nulls.SKIP)
        public Builder familyName(Optional<String> familyName) {
            this.familyName = familyName;
            return this;
        }

        public Builder familyName(String familyName) {
            this.familyName = Optional.ofNullable(familyName);
            return this;
        }

        @JsonSetter(value = "user_id", nulls = Nulls.SKIP)
        public Builder userId(Optional<String> userId) {
            this.userId = userId;
            return this;
        }

        public Builder userId(String userId) {
            this.userId = Optional.ofNullable(userId);
            return this;
        }

        @JsonSetter(value = "roles", nulls = Nulls.SKIP)
        public Builder roles(Optional<List<OrgMemberRole>> roles) {
            this.roles = roles;
            return this;
        }

        public Builder roles(List<OrgMemberRole> roles) {
            this.roles = Optional.ofNullable(roles);
            return this;
        }

        /**
         * <p>Date and time when this user was created (ISO_8601 format).</p>
         */
        @JsonSetter(value = "created_at", nulls = Nulls.SKIP)
        public Builder createdAt(Optional<OffsetDateTime> createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        public Builder createdAt(OffsetDateTime createdAt) {
            this.createdAt = Optional.ofNullable(createdAt);
            return this;
        }

        /**
         * <p>Date and time when this user was last updated (ISO_8601 format).</p>
         */
        @JsonSetter(value = "updated_at", nulls = Nulls.SKIP)
        public Builder updatedAt(Optional<OffsetDateTime> updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        public Builder updatedAt(OffsetDateTime updatedAt) {
            this.updatedAt = Optional.ofNullable(updatedAt);
            return this;
        }

        /**
         * <p>Last date and time this user logged in (ISO_8601 format).</p>
         */
        @JsonSetter(value = "last_login", nulls = Nulls.SKIP)
        public Builder lastLogin(Optional<OffsetDateTime> lastLogin) {
            this.lastLogin = lastLogin;
            return this;
        }

        public Builder lastLogin(OffsetDateTime lastLogin) {
            this.lastLogin = Optional.ofNullable(lastLogin);
            return this;
        }

        public OrgMember build() {
            return new OrgMember(
                    email,
                    name,
                    nickname,
                    givenName,
                    familyName,
                    userId,
                    roles,
                    createdAt,
                    updatedAt,
                    lastLogin,
                    additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
