/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.organization.identityproviders;

import com.auth0.client.myorganization.core.ClientOptions;
import com.auth0.client.myorganization.core.MediaTypes;
import com.auth0.client.myorganization.core.MyOrganizationApiException;
import com.auth0.client.myorganization.core.MyOrganizationApiHttpResponse;
import com.auth0.client.myorganization.core.MyOrganizationException;
import com.auth0.client.myorganization.core.ObjectMappers;
import com.auth0.client.myorganization.core.RequestOptions;
import com.auth0.client.myorganization.errors.BadRequestError;
import com.auth0.client.myorganization.errors.ConflictError;
import com.auth0.client.myorganization.errors.ForbiddenError;
import com.auth0.client.myorganization.errors.NotFoundError;
import com.auth0.client.myorganization.errors.TooManyRequestsError;
import com.auth0.client.myorganization.errors.UnauthorizedError;
import com.auth0.client.myorganization.organization.identityproviders.types.CreateIdpDomainRequestContent;
import com.auth0.client.myorganization.types.CreateIdpDomainResponseContent;
import com.auth0.client.myorganization.types.ErrorResponseContent;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawDomainsClient {
    protected final ClientOptions clientOptions;

    public AsyncRawDomainsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Associate a domain with an Identity Provider specified by ID for this Organization. The domain must be claimed and verified.
     */
    public CompletableFuture<MyOrganizationApiHttpResponse<CreateIdpDomainResponseContent>> create(
            String idpId, CreateIdpDomainRequestContent request) {
        return create(idpId, request, null);
    }

    /**
     * Associate a domain with an Identity Provider specified by ID for this Organization. The domain must be claimed and verified.
     */
    public CompletableFuture<MyOrganizationApiHttpResponse<CreateIdpDomainResponseContent>> create(
            String idpId, CreateIdpDomainRequestContent request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("identity-providers")
                .addPathSegment(idpId)
                .addPathSegments("domains");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new MyOrganizationException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<MyOrganizationApiHttpResponse<CreateIdpDomainResponseContent>> future =
                new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new MyOrganizationApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBodyString, CreateIdpDomainResponseContent.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(
                                                responseBodyString, ErrorResponseContent.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(
                                                responseBodyString, ErrorResponseContent.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(
                                                responseBodyString, ErrorResponseContent.class),
                                        response));
                                return;
                            case 409:
                                future.completeExceptionally(new ConflictError(
                                        ObjectMappers.JSON_MAPPER.readValue(
                                                responseBodyString, ErrorResponseContent.class),
                                        response));
                                return;
                            case 429:
                                future.completeExceptionally(new TooManyRequestsError(
                                        ObjectMappers.JSON_MAPPER.readValue(
                                                responseBodyString, ErrorResponseContent.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new MyOrganizationApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(
                            new MyOrganizationException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new MyOrganizationException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Remove a domain specified by name from an Identity Provider specified by ID for this Organization.
     */
    public CompletableFuture<MyOrganizationApiHttpResponse<Void>> delete(String idpId, String domain) {
        return delete(idpId, domain, null);
    }

    /**
     * Remove a domain specified by name from an Identity Provider specified by ID for this Organization.
     */
    public CompletableFuture<MyOrganizationApiHttpResponse<Void>> delete(
            String idpId, String domain, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("identity-providers")
                .addPathSegment(idpId)
                .addPathSegments("domains")
                .addPathSegment(domain);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<MyOrganizationApiHttpResponse<Void>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        future.complete(new MyOrganizationApiHttpResponse<>(null, response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(
                                                responseBodyString, ErrorResponseContent.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(
                                                responseBodyString, ErrorResponseContent.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(
                                                responseBodyString, ErrorResponseContent.class),
                                        response));
                                return;
                            case 429:
                                future.completeExceptionally(new TooManyRequestsError(
                                        ObjectMappers.JSON_MAPPER.readValue(
                                                responseBodyString, ErrorResponseContent.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new MyOrganizationApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(
                            new MyOrganizationException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new MyOrganizationException("Network error executing HTTP request", e));
            }
        });
        return future;
    }
}
