/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.organization.identityproviders;

import com.auth0.client.myorganization.core.ClientOptions;
import com.auth0.client.myorganization.core.RequestOptions;
import com.auth0.client.myorganization.organization.identityproviders.types.CreateIdpDomainRequestContent;
import com.auth0.client.myorganization.types.CreateIdpDomainResponseContent;
import java.util.concurrent.CompletableFuture;

public class AsyncDomainsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawDomainsClient rawClient;

    public AsyncDomainsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawDomainsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawDomainsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Associate a domain with an Identity Provider specified by ID for this Organization. The domain must be claimed and verified.
     */
    public CompletableFuture<CreateIdpDomainResponseContent> create(
            String idpId, CreateIdpDomainRequestContent request) {
        return this.rawClient.create(idpId, request).thenApply(response -> response.body());
    }

    /**
     * Associate a domain with an Identity Provider specified by ID for this Organization. The domain must be claimed and verified.
     */
    public CompletableFuture<CreateIdpDomainResponseContent> create(
            String idpId, CreateIdpDomainRequestContent request, RequestOptions requestOptions) {
        return this.rawClient.create(idpId, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Remove a domain specified by name from an Identity Provider specified by ID for this Organization.
     */
    public CompletableFuture<Void> delete(String idpId, String domain) {
        return this.rawClient.delete(idpId, domain).thenApply(response -> response.body());
    }

    /**
     * Remove a domain specified by name from an Identity Provider specified by ID for this Organization.
     */
    public CompletableFuture<Void> delete(String idpId, String domain, RequestOptions requestOptions) {
        return this.rawClient.delete(idpId, domain, requestOptions).thenApply(response -> response.body());
    }
}
