/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.organization.domains;

import com.auth0.client.myorganization.core.ClientOptions;
import com.auth0.client.myorganization.core.RequestOptions;
import com.auth0.client.myorganization.types.OrgDomain;

public class VerifyClient {
    protected final ClientOptions clientOptions;

    private final RawVerifyClient rawClient;

    public VerifyClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawVerifyClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawVerifyClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Initiate the verification process for a domain specified by ID for this Organization.
     */
    public OrgDomain create(String domainId) {
        return this.rawClient.create(domainId).body();
    }

    /**
     * Initiate the verification process for a domain specified by ID for this Organization.
     */
    public OrgDomain create(String domainId, RequestOptions requestOptions) {
        return this.rawClient.create(domainId, requestOptions).body();
    }
}
