/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.organization.identityproviders.provisioning.types;

import com.auth0.client.myorganization.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateIdpProvisioningScimTokenRequestContent.Builder.class)
public final class CreateIdpProvisioningScimTokenRequestContent {
    private final Optional<Integer> tokenLifetime;

    private final Map<String, Object> additionalProperties;

    private CreateIdpProvisioningScimTokenRequestContent(
            Optional<Integer> tokenLifetime, Map<String, Object> additionalProperties) {
        this.tokenLifetime = tokenLifetime;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Lifetime of the token in seconds. Do not set for non-expiring tokens.
     */
    @JsonProperty("token_lifetime")
    public Optional<Integer> getTokenLifetime() {
        return tokenLifetime;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateIdpProvisioningScimTokenRequestContent
                && equalTo((CreateIdpProvisioningScimTokenRequestContent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateIdpProvisioningScimTokenRequestContent other) {
        return tokenLifetime.equals(other.tokenLifetime);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.tokenLifetime);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Integer> tokenLifetime = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(CreateIdpProvisioningScimTokenRequestContent other) {
            tokenLifetime(other.getTokenLifetime());
            return this;
        }

        /**
         * <p>Lifetime of the token in seconds. Do not set for non-expiring tokens.</p>
         */
        @JsonSetter(value = "token_lifetime", nulls = Nulls.SKIP)
        public Builder tokenLifetime(Optional<Integer> tokenLifetime) {
            this.tokenLifetime = tokenLifetime;
            return this;
        }

        public Builder tokenLifetime(Integer tokenLifetime) {
            this.tokenLifetime = Optional.ofNullable(tokenLifetime);
            return this;
        }

        public CreateIdpProvisioningScimTokenRequestContent build() {
            return new CreateIdpProvisioningScimTokenRequestContent(tokenLifetime, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
