/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.organization;

import com.auth0.client.myorganization.core.ClientOptions;
import com.auth0.client.myorganization.core.RequestOptions;
import com.auth0.client.myorganization.organization.types.ListOrganizationUserStoresRequestParameters;
import com.auth0.client.myorganization.types.ListUserStoresResponseContent;
import java.util.concurrent.CompletableFuture;

public class AsyncUserStoresClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawUserStoresClient rawClient;

    public AsyncUserStoresClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawUserStoresClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawUserStoresClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieve the user stores for the associated Organization.
     */
    public CompletableFuture<ListUserStoresResponseContent> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    /**
     * Retrieve the user stores for the associated Organization.
     */
    public CompletableFuture<ListUserStoresResponseContent> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieve the user stores for the associated Organization.
     */
    public CompletableFuture<ListUserStoresResponseContent> list(ListOrganizationUserStoresRequestParameters request) {
        return this.rawClient.list(request).thenApply(response -> response.body());
    }

    /**
     * Retrieve the user stores for the associated Organization.
     */
    public CompletableFuture<ListUserStoresResponseContent> list(
            ListOrganizationUserStoresRequestParameters request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
    }
}
