/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.organization;

import com.auth0.client.myorganization.core.ClientOptions;
import com.auth0.client.myorganization.core.RequestOptions;
import com.auth0.client.myorganization.core.SyncPagingIterable;
import com.auth0.client.myorganization.organization.types.CreateMemberInvitationRequestContent;
import com.auth0.client.myorganization.organization.types.GetMemberInvitationRequestParameters;
import com.auth0.client.myorganization.organization.types.ListMemberInvitationsRequestParameters;
import com.auth0.client.myorganization.types.MemberInvitation;
import java.util.List;
import java.util.concurrent.CompletableFuture;

public class AsyncInvitationsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawInvitationsClient rawClient;

    public AsyncInvitationsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawInvitationsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawInvitationsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieve a list of all member invitations for this Organization.
     */
    public CompletableFuture<SyncPagingIterable<MemberInvitation>> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    /**
     * Retrieve a list of all member invitations for this Organization.
     */
    public CompletableFuture<SyncPagingIterable<MemberInvitation>> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieve a list of all member invitations for this Organization.
     */
    public CompletableFuture<SyncPagingIterable<MemberInvitation>> list(
            ListMemberInvitationsRequestParameters request) {
        return this.rawClient.list(request).thenApply(response -> response.body());
    }

    /**
     * Retrieve a list of all member invitations for this Organization.
     */
    public CompletableFuture<SyncPagingIterable<MemberInvitation>> list(
            ListMemberInvitationsRequestParameters request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Create one or more member invitations for this Organization. If an active invitation already exists for a user, generating a new invitation will automatically revoke any outstanding invitations for that user. Roles specified in the payload will be granted to the user upon acceptance of the invitation.
     */
    public CompletableFuture<List<MemberInvitation>> create(CreateMemberInvitationRequestContent request) {
        return this.rawClient.create(request).thenApply(response -> response.body());
    }

    /**
     * Create one or more member invitations for this Organization. If an active invitation already exists for a user, generating a new invitation will automatically revoke any outstanding invitations for that user. Roles specified in the payload will be granted to the user upon acceptance of the invitation.
     */
    public CompletableFuture<List<MemberInvitation>> create(
            CreateMemberInvitationRequestContent request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieve details of a member invitation specified by ID for this Organization.
     */
    public CompletableFuture<MemberInvitation> get(String invitationId) {
        return this.rawClient.get(invitationId).thenApply(response -> response.body());
    }

    /**
     * Retrieve details of a member invitation specified by ID for this Organization.
     */
    public CompletableFuture<MemberInvitation> get(String invitationId, RequestOptions requestOptions) {
        return this.rawClient.get(invitationId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieve details of a member invitation specified by ID for this Organization.
     */
    public CompletableFuture<MemberInvitation> get(String invitationId, GetMemberInvitationRequestParameters request) {
        return this.rawClient.get(invitationId, request).thenApply(response -> response.body());
    }

    /**
     * Retrieve details of a member invitation specified by ID for this Organization.
     */
    public CompletableFuture<MemberInvitation> get(
            String invitationId, GetMemberInvitationRequestParameters request, RequestOptions requestOptions) {
        return this.rawClient.get(invitationId, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Revoke a member invitation specified by ID for this Organization.
     */
    public CompletableFuture<Void> delete(String invitationId) {
        return this.rawClient.delete(invitationId).thenApply(response -> response.body());
    }

    /**
     * Revoke a member invitation specified by ID for this Organization.
     */
    public CompletableFuture<Void> delete(String invitationId, RequestOptions requestOptions) {
        return this.rawClient.delete(invitationId, requestOptions).thenApply(response -> response.body());
    }
}
