/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.organization;

import com.auth0.client.myorganization.core.ClientOptions;
import com.auth0.client.myorganization.core.RequestOptions;
import com.auth0.client.myorganization.core.Suppliers;
import com.auth0.client.myorganization.core.SyncPagingIterable;
import com.auth0.client.myorganization.organization.members.AsyncRolesClient;
import com.auth0.client.myorganization.organization.types.GetOrganizationMemberRequestParameters;
import com.auth0.client.myorganization.organization.types.ListOrganizationMembersRequestParameters;
import com.auth0.client.myorganization.types.OrgMember;
import java.util.concurrent.CompletableFuture;
import java.util.function.Supplier;

public class AsyncMembersClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawMembersClient rawClient;

    protected final Supplier<AsyncRolesClient> rolesClient;

    public AsyncMembersClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawMembersClient(clientOptions);
        this.rolesClient = Suppliers.memoize(() -> new AsyncRolesClient(clientOptions));
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawMembersClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieve a list of all members for this Organization. The <code>roles</code> field is only included for each member when the token also carries the <code>read:my_org:member_roles</code> scope; without that scope the <code>roles</code> field is omitted from the response.
     */
    public CompletableFuture<SyncPagingIterable<OrgMember>> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    /**
     * Retrieve a list of all members for this Organization. The <code>roles</code> field is only included for each member when the token also carries the <code>read:my_org:member_roles</code> scope; without that scope the <code>roles</code> field is omitted from the response.
     */
    public CompletableFuture<SyncPagingIterable<OrgMember>> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieve a list of all members for this Organization. The <code>roles</code> field is only included for each member when the token also carries the <code>read:my_org:member_roles</code> scope; without that scope the <code>roles</code> field is omitted from the response.
     */
    public CompletableFuture<SyncPagingIterable<OrgMember>> list(ListOrganizationMembersRequestParameters request) {
        return this.rawClient.list(request).thenApply(response -> response.body());
    }

    /**
     * Retrieve a list of all members for this Organization. The <code>roles</code> field is only included for each member when the token also carries the <code>read:my_org:member_roles</code> scope; without that scope the <code>roles</code> field is omitted from the response.
     */
    public CompletableFuture<SyncPagingIterable<OrgMember>> list(
            ListOrganizationMembersRequestParameters request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieve details of a member specified by user ID for this Organization.
     */
    public CompletableFuture<OrgMember> get(String userId) {
        return this.rawClient.get(userId).thenApply(response -> response.body());
    }

    /**
     * Retrieve details of a member specified by user ID for this Organization.
     */
    public CompletableFuture<OrgMember> get(String userId, RequestOptions requestOptions) {
        return this.rawClient.get(userId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieve details of a member specified by user ID for this Organization.
     */
    public CompletableFuture<OrgMember> get(String userId, GetOrganizationMemberRequestParameters request) {
        return this.rawClient.get(userId, request).thenApply(response -> response.body());
    }

    /**
     * Retrieve details of a member specified by user ID for this Organization.
     */
    public CompletableFuture<OrgMember> get(
            String userId, GetOrganizationMemberRequestParameters request, RequestOptions requestOptions) {
        return this.rawClient.get(userId, request, requestOptions).thenApply(response -> response.body());
    }

    public AsyncRolesClient roles() {
        return this.rolesClient.get();
    }
}
