/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.organization;

import com.auth0.client.myorganization.core.ClientOptions;
import com.auth0.client.myorganization.core.RequestOptions;
import com.auth0.client.myorganization.core.Suppliers;
import com.auth0.client.myorganization.core.SyncPagingIterable;
import com.auth0.client.myorganization.organization.domains.IdentityProvidersClient;
import com.auth0.client.myorganization.organization.domains.VerifyClient;
import com.auth0.client.myorganization.organization.types.CreateOrganizationDomainRequestContent;
import com.auth0.client.myorganization.organization.types.ListOrganizationDomainsRequestParameters;
import com.auth0.client.myorganization.types.OrgDomain;
import java.util.function.Supplier;

public class DomainsClient {
    protected final ClientOptions clientOptions;

    private final RawDomainsClient rawClient;

    protected final Supplier<VerifyClient> verifyClient;

    protected final Supplier<IdentityProvidersClient> identityProvidersClient;

    public DomainsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawDomainsClient(clientOptions);
        this.verifyClient = Suppliers.memoize(() -> new VerifyClient(clientOptions));
        this.identityProvidersClient = Suppliers.memoize(() -> new IdentityProvidersClient(clientOptions));
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawDomainsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieve a list of all pending and verified domains for this Organization.
     */
    public SyncPagingIterable<OrgDomain> list() {
        return this.rawClient.list().body();
    }

    /**
     * Retrieve a list of all pending and verified domains for this Organization.
     */
    public SyncPagingIterable<OrgDomain> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).body();
    }

    /**
     * Retrieve a list of all pending and verified domains for this Organization.
     */
    public SyncPagingIterable<OrgDomain> list(ListOrganizationDomainsRequestParameters request) {
        return this.rawClient.list(request).body();
    }

    /**
     * Retrieve a list of all pending and verified domains for this Organization.
     */
    public SyncPagingIterable<OrgDomain> list(
            ListOrganizationDomainsRequestParameters request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).body();
    }

    /**
     * Create a new domain for this Organization.
     */
    public OrgDomain create(CreateOrganizationDomainRequestContent request) {
        return this.rawClient.create(request).body();
    }

    /**
     * Create a new domain for this Organization.
     */
    public OrgDomain create(CreateOrganizationDomainRequestContent request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).body();
    }

    /**
     * Retrieve details of a domain specified by ID for this Organization.
     */
    public OrgDomain get(String domainId) {
        return this.rawClient.get(domainId).body();
    }

    /**
     * Retrieve details of a domain specified by ID for this Organization.
     */
    public OrgDomain get(String domainId, RequestOptions requestOptions) {
        return this.rawClient.get(domainId, requestOptions).body();
    }

    /**
     * Remove a domain specified by ID from this Organization.
     */
    public void delete(String domainId) {
        this.rawClient.delete(domainId).body();
    }

    /**
     * Remove a domain specified by ID from this Organization.
     */
    public void delete(String domainId, RequestOptions requestOptions) {
        this.rawClient.delete(domainId, requestOptions).body();
    }

    public VerifyClient verify() {
        return this.verifyClient.get();
    }

    public IdentityProvidersClient identityProviders() {
        return this.identityProvidersClient.get();
    }
}
