/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.organization;

import com.auth0.client.myorganization.core.ClientOptions;
import com.auth0.client.myorganization.core.RequestOptions;
import com.auth0.client.myorganization.core.Suppliers;
import com.auth0.client.myorganization.organization.identityproviders.DomainsClient;
import com.auth0.client.myorganization.organization.identityproviders.ProvisioningClient;
import com.auth0.client.myorganization.types.IdpKnownRequest;
import com.auth0.client.myorganization.types.IdpKnownResponse;
import com.auth0.client.myorganization.types.IdpUpdateKnownRequest;
import com.auth0.client.myorganization.types.IdpUpdateKnownResponse;
import com.auth0.client.myorganization.types.ListIdentityProvidersResponseContent;
import java.util.Map;
import java.util.function.Supplier;

public class IdentityProvidersClient {
    protected final ClientOptions clientOptions;

    private final RawIdentityProvidersClient rawClient;

    protected final Supplier<DomainsClient> domainsClient;

    protected final Supplier<ProvisioningClient> provisioningClient;

    public IdentityProvidersClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawIdentityProvidersClient(clientOptions);
        this.domainsClient = Suppliers.memoize(() -> new DomainsClient(clientOptions));
        this.provisioningClient = Suppliers.memoize(() -> new ProvisioningClient(clientOptions));
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawIdentityProvidersClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieve a list of all Identity Providers for this Organization.
     */
    public ListIdentityProvidersResponseContent list() {
        return this.rawClient.list().body();
    }

    /**
     * Retrieve a list of all Identity Providers for this Organization.
     */
    public ListIdentityProvidersResponseContent list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).body();
    }

    /**
     * Create a new Identity Provider for this Organization.
     */
    public IdpKnownResponse create(IdpKnownRequest request) {
        return this.rawClient.create(request).body();
    }

    /**
     * Create a new Identity Provider for this Organization.
     */
    public IdpKnownResponse create(IdpKnownRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).body();
    }

    /**
     * Retrieve details of an Identity Provider specified by ID for this Organization.
     */
    public IdpKnownResponse get(String idpId) {
        return this.rawClient.get(idpId).body();
    }

    /**
     * Retrieve details of an Identity Provider specified by ID for this Organization.
     */
    public IdpKnownResponse get(String idpId, RequestOptions requestOptions) {
        return this.rawClient.get(idpId, requestOptions).body();
    }

    /**
     * Delete an Identity Provider specified by ID from this Organization. This will remove the association and delete the underlying Identity Provider. Members will no longer be able to authenticate using this Identity Provider.
     */
    public void delete(String idpId) {
        this.rawClient.delete(idpId).body();
    }

    /**
     * Delete an Identity Provider specified by ID from this Organization. This will remove the association and delete the underlying Identity Provider. Members will no longer be able to authenticate using this Identity Provider.
     */
    public void delete(String idpId, RequestOptions requestOptions) {
        this.rawClient.delete(idpId, requestOptions).body();
    }

    /**
     * Update the details of an Identity Provider specified by ID for this Organization.
     */
    public IdpUpdateKnownResponse update(String idpId, IdpUpdateKnownRequest request) {
        return this.rawClient.update(idpId, request).body();
    }

    /**
     * Update the details of an Identity Provider specified by ID for this Organization.
     */
    public IdpUpdateKnownResponse update(String idpId, IdpUpdateKnownRequest request, RequestOptions requestOptions) {
        return this.rawClient.update(idpId, request, requestOptions).body();
    }

    /**
     * Refresh the attribute mapping for an Identity Provider specified by ID for this Organization. Mappings are reset to the admin-defined defaults.
     */
    public IdpKnownResponse updateAttributes(String idpId, Map<String, Object> request) {
        return this.rawClient.updateAttributes(idpId, request).body();
    }

    /**
     * Refresh the attribute mapping for an Identity Provider specified by ID for this Organization. Mappings are reset to the admin-defined defaults.
     */
    public IdpKnownResponse updateAttributes(String idpId, Map<String, Object> request, RequestOptions requestOptions) {
        return this.rawClient.updateAttributes(idpId, request, requestOptions).body();
    }

    /**
     * Remove an Identity Provider specified by ID from this Organization. This only removes the association; the underlying Identity Provider is not deleted. Members will no longer be able to authenticate using this Identity Provider.
     */
    public void detach(String idpId) {
        this.rawClient.detach(idpId).body();
    }

    /**
     * Remove an Identity Provider specified by ID from this Organization. This only removes the association; the underlying Identity Provider is not deleted. Members will no longer be able to authenticate using this Identity Provider.
     */
    public void detach(String idpId, RequestOptions requestOptions) {
        this.rawClient.detach(idpId, requestOptions).body();
    }

    public DomainsClient domains() {
        return this.domainsClient.get();
    }

    public ProvisioningClient provisioning() {
        return this.provisioningClient.get();
    }
}
