/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.organization;

import com.auth0.client.myorganization.core.ClientOptions;
import com.auth0.client.myorganization.core.RequestOptions;
import com.auth0.client.myorganization.core.Suppliers;
import com.auth0.client.myorganization.core.SyncPagingIterable;
import com.auth0.client.myorganization.organization.invitations.RolesClient;
import com.auth0.client.myorganization.organization.types.CreateMemberInvitationRequestContent;
import com.auth0.client.myorganization.organization.types.DeleteMemberInvitationsRequestContent;
import com.auth0.client.myorganization.organization.types.GetMemberInvitationRequestParameters;
import com.auth0.client.myorganization.organization.types.ListMemberInvitationsRequestParameters;
import com.auth0.client.myorganization.types.MemberInvitation;
import java.util.List;
import java.util.function.Supplier;

public class InvitationsClient {
    protected final ClientOptions clientOptions;

    private final RawInvitationsClient rawClient;

    protected final Supplier<RolesClient> rolesClient;

    public InvitationsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawInvitationsClient(clientOptions);
        this.rolesClient = Suppliers.memoize(() -> new RolesClient(clientOptions));
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawInvitationsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieve a list of all member invitations for this Organization.
     */
    public SyncPagingIterable<MemberInvitation> list() {
        return this.rawClient.list().body();
    }

    /**
     * Retrieve a list of all member invitations for this Organization.
     */
    public SyncPagingIterable<MemberInvitation> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).body();
    }

    /**
     * Retrieve a list of all member invitations for this Organization.
     */
    public SyncPagingIterable<MemberInvitation> list(ListMemberInvitationsRequestParameters request) {
        return this.rawClient.list(request).body();
    }

    /**
     * Retrieve a list of all member invitations for this Organization.
     */
    public SyncPagingIterable<MemberInvitation> list(
            ListMemberInvitationsRequestParameters request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).body();
    }

    /**
     * Create one or more member invitations for this Organization. If an active invitation already exists for a user, generating a new invitation will automatically revoke any outstanding invitations for that user. Roles specified in the payload will be granted to the user upon acceptance of the invitation.
     */
    public List<MemberInvitation> create(CreateMemberInvitationRequestContent request) {
        return this.rawClient.create(request).body();
    }

    /**
     * Create one or more member invitations for this Organization. If an active invitation already exists for a user, generating a new invitation will automatically revoke any outstanding invitations for that user. Roles specified in the payload will be granted to the user upon acceptance of the invitation.
     */
    public List<MemberInvitation> create(CreateMemberInvitationRequestContent request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).body();
    }

    /**
     * Revoke a set of member invitations specified by IDs for this Organization.
     */
    public void delete(DeleteMemberInvitationsRequestContent request) {
        this.rawClient.delete(request).body();
    }

    /**
     * Revoke a set of member invitations specified by IDs for this Organization.
     */
    public void delete(DeleteMemberInvitationsRequestContent request, RequestOptions requestOptions) {
        this.rawClient.delete(request, requestOptions).body();
    }

    /**
     * Retrieve details of a member invitation specified by ID for this Organization.
     */
    public MemberInvitation get(String invitationId) {
        return this.rawClient.get(invitationId).body();
    }

    /**
     * Retrieve details of a member invitation specified by ID for this Organization.
     */
    public MemberInvitation get(String invitationId, RequestOptions requestOptions) {
        return this.rawClient.get(invitationId, requestOptions).body();
    }

    /**
     * Retrieve details of a member invitation specified by ID for this Organization.
     */
    public MemberInvitation get(String invitationId, GetMemberInvitationRequestParameters request) {
        return this.rawClient.get(invitationId, request).body();
    }

    /**
     * Retrieve details of a member invitation specified by ID for this Organization.
     */
    public MemberInvitation get(
            String invitationId, GetMemberInvitationRequestParameters request, RequestOptions requestOptions) {
        return this.rawClient.get(invitationId, request, requestOptions).body();
    }

    public RolesClient roles() {
        return this.rolesClient.get();
    }
}
