/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.organization;

import com.auth0.client.myorganization.core.ClientOptions;
import com.auth0.client.myorganization.core.RequestOptions;
import com.auth0.client.myorganization.core.Suppliers;
import com.auth0.client.myorganization.core.SyncPagingIterable;
import com.auth0.client.myorganization.organization.members.RolesClient;
import com.auth0.client.myorganization.organization.types.GetOrganizationMemberRequestParameters;
import com.auth0.client.myorganization.organization.types.ListOrganizationMembersRequestParameters;
import com.auth0.client.myorganization.types.OrgMember;
import java.util.function.Supplier;

public class MembersClient {
    protected final ClientOptions clientOptions;

    private final RawMembersClient rawClient;

    protected final Supplier<RolesClient> rolesClient;

    public MembersClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawMembersClient(clientOptions);
        this.rolesClient = Suppliers.memoize(() -> new RolesClient(clientOptions));
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawMembersClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieve a list of all members for this Organization. The <code>roles</code> field is only included for each member when the token also carries the <code>read:my_org:member_roles</code> scope; without that scope the <code>roles</code> field is omitted from the response.
     */
    public SyncPagingIterable<OrgMember> list() {
        return this.rawClient.list().body();
    }

    /**
     * Retrieve a list of all members for this Organization. The <code>roles</code> field is only included for each member when the token also carries the <code>read:my_org:member_roles</code> scope; without that scope the <code>roles</code> field is omitted from the response.
     */
    public SyncPagingIterable<OrgMember> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).body();
    }

    /**
     * Retrieve a list of all members for this Organization. The <code>roles</code> field is only included for each member when the token also carries the <code>read:my_org:member_roles</code> scope; without that scope the <code>roles</code> field is omitted from the response.
     */
    public SyncPagingIterable<OrgMember> list(ListOrganizationMembersRequestParameters request) {
        return this.rawClient.list(request).body();
    }

    /**
     * Retrieve a list of all members for this Organization. The <code>roles</code> field is only included for each member when the token also carries the <code>read:my_org:member_roles</code> scope; without that scope the <code>roles</code> field is omitted from the response.
     */
    public SyncPagingIterable<OrgMember> list(
            ListOrganizationMembersRequestParameters request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).body();
    }

    /**
     * Retrieve details of a member specified by user ID for this Organization.
     */
    public OrgMember get(String userId) {
        return this.rawClient.get(userId).body();
    }

    /**
     * Retrieve details of a member specified by user ID for this Organization.
     */
    public OrgMember get(String userId, RequestOptions requestOptions) {
        return this.rawClient.get(userId, requestOptions).body();
    }

    /**
     * Retrieve details of a member specified by user ID for this Organization.
     */
    public OrgMember get(String userId, GetOrganizationMemberRequestParameters request) {
        return this.rawClient.get(userId, request).body();
    }

    /**
     * Retrieve details of a member specified by user ID for this Organization.
     */
    public OrgMember get(String userId, GetOrganizationMemberRequestParameters request, RequestOptions requestOptions) {
        return this.rawClient.get(userId, request, requestOptions).body();
    }

    public RolesClient roles() {
        return this.rolesClient.get();
    }
}
