/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.organization;

import com.auth0.client.myorganization.core.ClientOptions;
import com.auth0.client.myorganization.core.MyOrganizationApiException;
import com.auth0.client.myorganization.core.MyOrganizationApiHttpResponse;
import com.auth0.client.myorganization.core.MyOrganizationException;
import com.auth0.client.myorganization.core.ObjectMappers;
import com.auth0.client.myorganization.core.QueryStringMapper;
import com.auth0.client.myorganization.core.RequestOptions;
import com.auth0.client.myorganization.errors.BadRequestError;
import com.auth0.client.myorganization.errors.ForbiddenError;
import com.auth0.client.myorganization.errors.NotFoundError;
import com.auth0.client.myorganization.errors.TooManyRequestsError;
import com.auth0.client.myorganization.errors.UnauthorizedError;
import com.auth0.client.myorganization.organization.types.ListOrganizationUserStoresRequestParameters;
import com.auth0.client.myorganization.types.ErrorResponseContent;
import com.auth0.client.myorganization.types.ListUserStoresResponseContent;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawUserStoresClient {
    protected final ClientOptions clientOptions;

    public RawUserStoresClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Retrieve the user stores for the associated Organization.
     */
    public MyOrganizationApiHttpResponse<ListUserStoresResponseContent> list() {
        return list(ListOrganizationUserStoresRequestParameters.builder().build());
    }

    /**
     * Retrieve the user stores for the associated Organization.
     */
    public MyOrganizationApiHttpResponse<ListUserStoresResponseContent> list(RequestOptions requestOptions) {
        return list(ListOrganizationUserStoresRequestParameters.builder().build(), requestOptions);
    }

    /**
     * Retrieve the user stores for the associated Organization.
     */
    public MyOrganizationApiHttpResponse<ListUserStoresResponseContent> list(
            ListOrganizationUserStoresRequestParameters request) {
        return list(request, null);
    }

    /**
     * Retrieve the user stores for the associated Organization.
     */
    public MyOrganizationApiHttpResponse<ListUserStoresResponseContent> list(
            ListOrganizationUserStoresRequestParameters request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("user-stores");
        if (!request.getIsEnabled().isAbsent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "is_enabled", request.getIsEnabled().orElse(null), false);
        }
        if (request.getMemberAccessLevel().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl,
                    "member_access_level",
                    request.getMemberAccessLevel().get(),
                    true);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new MyOrganizationApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ListUserStoresResponseContent.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponseContent.class),
                                response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponseContent.class),
                                response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponseContent.class),
                                response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponseContent.class),
                                response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new MyOrganizationApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new MyOrganizationException("Network error executing HTTP request", e);
        }
    }
}
