/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.organization;

import com.auth0.client.myorganization.core.ClientOptions;
import com.auth0.client.myorganization.core.RequestOptions;
import com.auth0.client.myorganization.core.SyncPagingIterable;
import com.auth0.client.myorganization.organization.types.ListRolesRequestParameters;
import com.auth0.client.myorganization.types.Role;

public class RolesClient {
    protected final ClientOptions clientOptions;

    private final RawRolesClient rawClient;

    public RolesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawRolesClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawRolesClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieve the list of roles available for binding to members and invitations for this Organization. Only roles made visible to this Organization by the Tenant Admin are returned.
     */
    public SyncPagingIterable<Role> list() {
        return this.rawClient.list().body();
    }

    /**
     * Retrieve the list of roles available for binding to members and invitations for this Organization. Only roles made visible to this Organization by the Tenant Admin are returned.
     */
    public SyncPagingIterable<Role> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).body();
    }

    /**
     * Retrieve the list of roles available for binding to members and invitations for this Organization. Only roles made visible to this Organization by the Tenant Admin are returned.
     */
    public SyncPagingIterable<Role> list(ListRolesRequestParameters request) {
        return this.rawClient.list(request).body();
    }

    /**
     * Retrieve the list of roles available for binding to members and invitations for this Organization. Only roles made visible to this Organization by the Tenant Admin are returned.
     */
    public SyncPagingIterable<Role> list(ListRolesRequestParameters request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).body();
    }
}
