/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.errors;

import com.auth0.client.myorganization.core.MyOrganizationApiException;
import okhttp3.Response;

public final class BadRequestError extends MyOrganizationApiException {
    /**
     * The body of the response that triggered the exception.
     */
    private final Object body;

    public BadRequestError(Object body) {
        super("BadRequestError", 400, body);
        this.body = body;
    }

    public BadRequestError(Object body, Response rawResponse) {
        super("BadRequestError", 400, body, rawResponse);
        this.body = body;
    }

    /**
     * @return the body
     */
    @java.lang.Override
    public Object body() {
        return this.body;
    }
}
