/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.myorganization.errors;

import com.auth0.client.myorganization.core.MyOrganizationApiException;
import com.auth0.client.myorganization.types.ErrorResponseContent;
import okhttp3.Response;

public final class NotFoundError extends MyOrganizationApiException {
    /**
     * The body of the response that triggered the exception.
     */
    private final ErrorResponseContent body;

    public NotFoundError(ErrorResponseContent body) {
        super("NotFoundError", 404, body);
        this.body = body;
    }

    public NotFoundError(ErrorResponseContent body, Response rawResponse) {
        super("NotFoundError", 404, body, rawResponse);
        this.body = body;
    }

    /**
     * @return the body
     */
    @java.lang.Override
    public ErrorResponseContent body() {
        return this.body;
    }
}
